import type { CareerCosmetic } from "@/types/avatar";

export const CAREER_COSMETICS: Record<string, CareerCosmetic> = {
  software: {
    career: "software",
    label: "Ingeniería de Software",
    accessory: "laptop",
    accessoryColor: "#185FA5",
    hat: "none",
    badge: "</>",
    background: "abstract",
    accentColor: "#378ADD",
    description: "Laptop y código",
  },
  medicina: {
    career: "medicina",
    label: "Medicina",
    accessory: "stethoscope",
    accessoryColor: "#185FA5",
    hat: "surgical-cap",
    badge: "⚕",
    background: "lab",
    accentColor: "#378ADD",
    description: "Estetoscopio y gorra quirúrgica",
  },
  derecho: {
    career: "derecho",
    label: "Derecho",
    accessory: "scales",
    accessoryColor: "#854F0B",
    hat: "lawyer-wig",
    badge: "⚖",
    background: "library",
    accentColor: "#EF9F27",
    description: "Peluca de abogado y balanza de justicia",
  },
  administracion: {
    career: "administracion",
    label: "Administración",
    accessory: "briefcase",
    accessoryColor: "#185FA5",
    hat: "tie",
    badge: "◈",
    background: "city",
    accentColor: "#378ADD",
    description: "Corbata ejecutiva y maletín",
  },
  contabilidad: {
    career: "contabilidad",
    label: "Contabilidad",
    accessory: "calculator",
    accessoryColor: "#0891b2",
    hat: "reading-glasses",
    badge: "∑",
    background: "city",
    accentColor: "#22D3EE",
    description: "Calculadora y gafas de lectura",
  },
  "ingenieria-civil": {
    career: "ingenieria-civil",
    label: "Ingeniería Civil",
    accessory: "hard-hat",
    accessoryColor: "#dc2626",
    hat: "hard-hat",
    badge: "🏗",
    background: "city",
    accentColor: "#EF4444",
    description: "Casco de obra y planos",
  },
  arquitectura: {
    career: "arquitectura",
    label: "Arquitectura y Urbanismo Ambiental",
    accessory: "ruler",
    accessoryColor: "#3B6D11",
    hat: "beret",
    badge: "⌂",
    background: "city",
    accentColor: "#97C459",
    description: "Boina y escuadra de arquitecto",
  },
  psicologia: {
    career: "psicologia",
    label: "Psicología",
    accessory: "brain",
    accessoryColor: "#533AB7",
    hat: "none",
    badge: "Ψ",
    background: "nature",
    accentColor: "#7F77DD",
    description: "Símbolo psi y libro de apuntes",
  },
  marketing: {
    career: "marketing",
    label: "Marketing y Gestión de Medios",
    accessory: "megaphone",
    accessoryColor: "#993556",
    hat: "none",
    badge: "◉",
    background: "abstract",
    accentColor: "#D4537E",
    description: "Megáfono y estrategia",
  },
  "diseno-ux": {
    career: "diseno-ux",
    label: "Diseño UX/UI",
    accessory: "palette",
    accessoryColor: "#db2777",
    hat: "beret",
    badge: "✦",
    background: "abstract",
    accentColor: "#F472B6",
    description: "Paleta de colores y prototipado",
  },
  enfermeria: {
    career: "enfermeria",
    label: "Enfermería",
    accessory: "syringe",
    accessoryColor: "#0891b2",
    hat: "surgical-cap",
    badge: "💉",
    background: "lab",
    accentColor: "#22D3EE",
    description: "Jeringa y gorro quirúrgico",
  },
  "ingenieria-industrial": {
    career: "ingenieria-industrial",
    label: "Ingeniería Industrial",
    accessory: "gear",
    accessoryColor: "#475569",
    hat: "hard-hat",
    badge: "⚙",
    background: "abstract",
    accentColor: "#94A3B8",
    description: "Engranaje y casco industrial",
  },
  economia: {
    career: "economia",
    label: "Economía y Finanzas",
    accessory: "chart",
    accessoryColor: "#16a34a",
    hat: "none",
    badge: "📈",
    background: "city",
    accentColor: "#4ADE80",
    description: "Gráficos y análisis financiero",
  },
  gastronomia: {
    career: "gastronomia",
    label: "Gastronomía",
    accessory: "chef-knife",
    accessoryColor: "#D85A30",
    hat: "chef-hat",
    badge: "♨",
    background: "nature",
    accentColor: "#F0997B",
    description: "Gorro de chef y cuchillo",
  },
  periodismo: {
    career: "periodismo",
    label: "Periodismo & Comunicación",
    accessory: "microphone",
    accessoryColor: "#1d4ed8",
    hat: "none",
    badge: "🎤",
    background: "city",
    accentColor: "#60A5FA",
    description: "Micrófono y libreta",
  },
  "ingenieria-minas": {
    career: "ingenieria-minas",
    label: "Ingeniería de Minas",
    accessory: "pickaxe",
    accessoryColor: "#92400e",
    hat: "hard-hat",
    badge: "⛏",
    background: "nature",
    accentColor: "#D97706",
    description: "Pico y casco minero",
  },
  odontologia: {
    career: "odontologia",
    label: "Odontología",
    accessory: "tooth",
    accessoryColor: "#0284c7",
    hat: "surgical-cap",
    badge: "🦷",
    background: "lab",
    accentColor: "#38BDF8",
    description: "Diente y gorro quirúrgico",
  },
  "ingenieria-ambiental": {
    career: "ingenieria-ambiental",
    label: "Ingeniería Ambiental",
    accessory: "leaf",
    accessoryColor: "#16a34a",
    hat: "none",
    badge: "🌿",
    background: "nature",
    accentColor: "#4ADE80",
    description: "Hoja y monitoreo ambiental",
  },
  educacion: {
    career: "educacion",
    label: "Educación & Pedagogía",
    accessory: "book",
    accessoryColor: "#7c3aed",
    hat: "mortarboard",
    badge: "📚",
    background: "library",
    accentColor: "#A78BFA",
    description: "Birrete y libros",
  },
  nutricion: {
    career: "nutricion",
    label: "Nutrición y Dietética",
    accessory: "apple",
    accessoryColor: "#16a34a",
    hat: "none",
    badge: "🥗",
    background: "nature",
    accentColor: "#4ADE80",
    description: "Manzana y plan nutricional",
  },
  turismo: {
    career: "turismo",
    label: "Turismo Sostenible y Hotelería",
    accessory: "airplane",
    accessoryColor: "#0891b2",
    hat: "none",
    badge: "✈",
    background: "sky",
    accentColor: "#22D3EE",
    description: "Avión y mapas turísticos",
  },
  "relaciones-internacionales": {
    career: "relaciones-internacionales",
    label: "Relaciones Internacionales",
    accessory: "handshake",
    accessoryColor: "#1d4ed8",
    hat: "tie",
    badge: "🌐",
    background: "city",
    accentColor: "#60A5FA",
    description: "Corbata y acuerdo diplomático",
  },
  veterinaria: {
    career: "veterinaria",
    label: "Medicina Veterinaria",
    accessory: "paw",
    accessoryColor: "#d97706",
    hat: "surgical-cap",
    badge: "🐾",
    background: "nature",
    accentColor: "#FBBF24",
    description: "Huella animal y medicamentos",
  },
  "administracion-negocios-internacionales": {
    career: "administracion-negocios-internacionales",
    label: "Administración y Negocios Internacionales",
    accessory: "globe",
    accessoryColor: "#2563eb",
    hat: "tie",
    badge: "🌍",
    background: "city",
    accentColor: "#60A5FA",
    description: "Globo terráqueo y corbata ejecutiva",
  },
  "biologia-marina": {
    career: "biologia-marina",
    label: "Biología Marina",
    accessory: "fish",
    accessoryColor: "#0d9488",
    hat: "none",
    badge: "🐠",
    background: "nature",
    accentColor: "#2DD4BF",
    description: "Peces y océano",
  },
  "ciencia-computacion": {
    career: "ciencia-computacion",
    label: "Ciencia de la Computación",
    accessory: "processor",
    accessoryColor: "#6d28d9",
    hat: "none",
    badge: "💻",
    background: "abstract",
    accentColor: "#8B5CF6",
    description: "Procesador y algoritmos",
  },
  "ciencias-comunicacion": {
    career: "ciencias-comunicacion",
    label: "Ciencias de la Comunicación",
    accessory: "microphone",
    accessoryColor: "#0891b2",
    hat: "none",
    badge: "🎙",
    background: "abstract",
    accentColor: "#22D3EE",
    description: "Micrófono y medios",
  },
  "comunicacion-publicidad": {
    career: "comunicacion-publicidad",
    label: "Comunicación y Publicidad",
    accessory: "megaphone",
    accessoryColor: "#e11d48",
    hat: "none",
    badge: "📢",
    background: "abstract",
    accentColor: "#FB7185",
    description: "Megáfono y campañas",
  },
  "educacion-inicial": {
    career: "educacion-inicial",
    label: "Educación Inicial",
    accessory: "blocks",
    accessoryColor: "#f43f5e",
    hat: "none",
    badge: "🧸",
    background: "nature",
    accentColor: "#FB7185",
    description: "Bloques de construcción",
  },
  "educacion-primaria": {
    career: "educacion-primaria",
    label: "Educación Primaria",
    accessory: "apple-desk",
    accessoryColor: "#eab308",
    hat: "none",
    badge: "📚",
    background: "library",
    accentColor: "#FBBF24",
    description: "Manzana para el maestro",
  },
  "ingenieria-biomedica": {
    career: "ingenieria-biomedica",
    label: "Ingeniería Biomédica",
    accessory: "dna",
    accessoryColor: "#0ea5e9",
    hat: "none",
    badge: "🦾",
    background: "lab",
    accentColor: "#38BDF8",
    description: "ADN y dispositivos médicos",
  },
  "ingenieria-ciberseguridad": {
    career: "ingenieria-ciberseguridad",
    label: "Ingeniería de Ciberseguridad",
    accessory: "shield",
    accessoryColor: "#1e293b",
    hat: "none",
    badge: "🔐",
    background: "abstract",
    accentColor: "#64748B",
    description: "Escudo y candado digital",
  },
  "ingenieria-diseno-grafico": {
    career: "ingenieria-diseno-grafico",
    label: "Ingeniería de Diseño Gráfico",
    accessory: "palette",
    accessoryColor: "#db2777",
    hat: "beret",
    badge: "🎨",
    background: "abstract",
    accentColor: "#F472B6",
    description: "Paleta de colores y tipografía",
  },
  "ingenieria-sistemas-informacion": {
    career: "ingenieria-sistemas-informacion",
    label: "Ingeniería de Sistemas de Información",
    accessory: "database",
    accessoryColor: "#0891b2",
    hat: "none",
    badge: "🗄",
    background: "abstract",
    accentColor: "#22D3EE",
    description: "Base de datos y sistemas",
  },
  "ingenieria-sistemas": {
    career: "ingenieria-sistemas",
    label: "Ingeniería de Sistemas",
    accessory: "gear",
    accessoryColor: "#475569",
    hat: "none",
    badge: "⚙",
    background: "abstract",
    accentColor: "#94A3B8",
    description: "Engranaje y servidores",
  },
  "ingenieria-transporte": {
    career: "ingenieria-transporte",
    label: "Ingeniería de Transporte",
    accessory: "train",
    accessoryColor: "#2563eb",
    hat: "hard-hat",
    badge: "🚆",
    background: "city",
    accentColor: "#60A5FA",
    description: "Tren y planos viales",
  },
  "ingenieria-economica-negocios": {
    career: "ingenieria-economica-negocios",
    label: "Ingeniería Económica y de Negocios",
    accessory: "money",
    accessoryColor: "#16a34a",
    hat: "tie",
    badge: "📈",
    background: "city",
    accentColor: "#4ADE80",
    description: "Gráficos financieros y corbata",
  },
  "ingenieria-electronica": {
    career: "ingenieria-electronica",
    label: "Ingeniería Electrónica",
    accessory: "circuit",
    accessoryColor: "#d97706",
    hat: "none",
    badge: "⚡",
    background: "abstract",
    accentColor: "#FBBF24",
    description: "Circuitos y voltaje",
  },
  "ingenieria-empresarial": {
    career: "ingenieria-empresarial",
    label: "Ingeniería Empresarial",
    accessory: "building",
    accessoryColor: "#7c3aed",
    hat: "tie",
    badge: "🏢",
    background: "city",
    accentColor: "#A78BFA",
    description: "Edificio corporativo",
  },
  "ingenieria-maritima": {
    career: "ingenieria-maritima",
    label: "Ingeniería Marítima",
    accessory: "anchor",
    accessoryColor: "#0d9488",
    hat: "hard-hat",
    badge: "⚓",
    background: "nature",
    accentColor: "#2DD4BF",
    description: "Ancla y puertos",
  },
  "ingenieria-mecanica": {
    career: "ingenieria-mecanica",
    label: "Ingeniería Mecánica",
    accessory: "bolt",
    accessoryColor: "#64748b",
    hat: "hard-hat",
    badge: "🔧",
    background: "abstract",
    accentColor: "#94A3B8",
    description: "Tuercas y maquinaria",
  },
  "ingenieria-mecatronica": {
    career: "ingenieria-mecatronica",
    label: "Ingeniería Mecatrónica",
    accessory: "robot",
    accessoryColor: "#0ea5e9",
    hat: "none",
    badge: "🤖",
    background: "abstract",
    accentColor: "#38BDF8",
    description: "Robot y automatización",
  },
  "ingenieria-naval": {
    career: "ingenieria-naval",
    label: "Ingeniería Naval",
    accessory: "ship",
    accessoryColor: "#1d4ed8",
    hat: "hard-hat",
    badge: "🚢",
    background: "nature",
    accentColor: "#60A5FA",
    description: "Buque y astillero",
  },
  obstetricia: {
    career: "obstetricia",
    label: "Obstetricia",
    accessory: "baby",
    accessoryColor: "#e11d48",
    hat: "surgical-cap",
    badge: "🤰",
    background: "lab",
    accentColor: "#FB7185",
    description: "Cuidado materno-infantil",
  },
  "psicologia-consumidor": {
    career: "psicologia-consumidor",
    label: "Psicología del Consumidor",
    accessory: "shopping-cart",
    accessoryColor: "#f43f5e",
    hat: "none",
    badge: "🛍",
    background: "abstract",
    accentColor: "#FB7185",
    description: "Carrito de compras",
  },
  "redes-telecomunicaciones": {
    career: "redes-telecomunicaciones",
    label: "Redes y Telecomunicaciones",
    accessory: "satellite",
    accessoryColor: "#0891b2",
    hat: "none",
    badge: "📡",
    background: "sky",
    accentColor: "#22D3EE",
    description: "Antena y señales",
  },
  "tecnologia-medica": {
    career: "tecnologia-medica",
    label: "Tecnología Médica",
    accessory: "xray",
    accessoryColor: "#0ea5e9",
    hat: "surgical-cap",
    badge: "🔬",
    background: "lab",
    accentColor: "#38BDF8",
    description: "Rayos X y diagnóstico",
  },
  "traduccion-interpretacion": {
    career: "traduccion-interpretacion",
    label: "Traducción e Interpretación",
    accessory: "book-open",
    accessoryColor: "#7c3aed",
    hat: "none",
    badge: "🌐",
    background: "library",
    accentColor: "#A78BFA",
    description: "Libros abiertos al mundo",
  },
};

export const SKIN_TONES: Record<string, { fill: string; shadow: string; label: string }> = {
  light:          { fill: "#FDDBB4", shadow: "#F0B97D", label: "Clara" },
  "medium-light": { fill: "#F5C18A", shadow: "#D99A5E", label: "Medio clara" },
  medium:         { fill: "#D4956A", shadow: "#B3744D", label: "Media" },
  "medium-dark":  { fill: "#A0623A", shadow: "#7D4928", label: "Medio oscura" },
  dark:           { fill: "#5C3317", shadow: "#3D2010", label: "Oscura" },
};

export const HAIR_COLORS: Record<string, { fill: string; label: string }> = {
  black:  { fill: "#1A1A1A", label: "Negro" },
  brown:  { fill: "#5C3317", label: "Castaño" },
  blonde: { fill: "#E8C97A", label: "Rubio" },
  red:    { fill: "#C0392B", label: "Rojo" },
  gray:   { fill: "#888780", label: "Gris" },
  white:  { fill: "#F1EFE8", label: "Blanco" },
};

export const EYE_COLORS: Record<string, { fill: string; label: string }> = {
  brown:  { fill: "#5C3317", label: "Café" },
  hazel:  { fill: "#7D6A2A", label: "Avellana" },
  green:  { fill: "#2E7D32", label: "Verde" },
  blue:   { fill: "#1565C0", label: "Azul" },
  gray:   { fill: "#607D8B", label: "Gris" },
};
