export type SkillLevel = "basico" | "intermedio" | "avanzado" | "experto";

export type SkillRequirement = {
  name: string;
  requiredLevel: SkillLevel;
  category: "tecnica" | "blanda" | "academica";
};

export type DayActivity = {
  time: string;
  activity: string;
  emoji: string;
};

export type Career = {
  id: string;
  title: string;
  area: string;
  emoji: string;
  color: string;
  lightBg: string;
  description: string;
  salary: string;
  salaryMin: number;
  skills: string[];
  skillRequirements: SkillRequirement[];
  dayInLife: DayActivity[];
  universities: string[];
  outlook: "Alta" | "Media" | "Estable";
  duration: string;
  nowDoing: string;
  scene: string[];
  tools: string[];
};

export const AREAS = [
  "Todos",
  "Tecnología",
  "Salud",
  "Derecho",
  "Negocios",
  "Diseño",
  "Ingeniería",
  "Educación",
  "Ciencias",
  "Gastronomía",
  "Humanidades",
];

export const careers: Career[] = [
  {
    id: "software",
    title: "Ingeniería de Software",
    area: "Tecnología",
    emoji: "💻",
    color: "#dc2626",
    lightBg: "#fff1f1",
    description:
      "Diseñas y construyes el software que mueve al mundo. Desde apps móviles hasta sistemas bancarios, tu código resuelve problemas reales.",
    salary: "S/. 4,000 – 15,000",
    salaryMin: 4000,
    skills: ["Programación", "Lógica", "Trabajo en equipo", "Aprendizaje continuo", "Resolución de problemas"],
    skillRequirements: [
      { name: "Programación", requiredLevel: "basico", category: "tecnica" },
      { name: "Lógica", requiredLevel: "basico", category: "academica" },
      { name: "Trabajo en equipo", requiredLevel: "basico", category: "blanda" },
      { name: "Aprendizaje continuo", requiredLevel: "basico", category: "blanda" },
      { name: "Resolución de problemas", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Daily standup con tu equipo (15 min)", emoji: "🤝" },
      { time: "9:30 am", activity: "Revisas el tablero de tareas y priorizas", emoji: "📋" },
      { time: "10:00 am", activity: "Programas una nueva funcionalidad", emoji: "⌨️" },
      { time: "1:00 pm", activity: "Almuerzo y scrolleas GitHub trends", emoji: "🍱" },
      { time: "2:00 pm", activity: "Code review del pull request de un colega", emoji: "🔍" },
      { time: "3:30 pm", activity: "Corriges bugs reportados en producción", emoji: "🐛" },
      { time: "5:00 pm", activity: "Deploy a staging y documentas cambios", emoji: "🚀" },
    ],
    universities: ["PUCP", "UNI", "UTEC", "U. Lima", "UPC", "UNMSM"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Escribiendo código en tu IDE favorito, probablemente VS Code con música lo-fi de fondo.",
    scene: ["💻", "⌨️", "🖥️", "☕", "🎧"],
    tools: ["React", "Python", "AWS", "Docker", "Git"],
  },
  {
    id: "medicina",
    title: "Medicina Humana",
    area: "Salud",
    emoji: "🩺",
    color: "#059669",
    lightBg: "#f0fdf4",
    description:
      "Salvas vidas. Diagnósticas, tratas y acompañas a personas en sus momentos más vulnerables. Es la carrera más demandante y más humana.",
    salary: "S/. 5,000 – 18,000",
    salaryMin: 5000,
    skills: ["Empatía", "Precisión", "Resistencia", "Toma de decisiones", "Memorización"],
    skillRequirements: [
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Precisión", requiredLevel: "basico", category: "blanda" },
      { name: "Resistencia", requiredLevel: "intermedio", category: "blanda" },
      { name: "Toma de decisiones", requiredLevel: "basico", category: "blanda" },
      { name: "Memorización", requiredLevel: "intermedio", category: "academica" },
    ],
    dayInLife: [
      { time: "7:00 am", activity: "Visita matutina a pacientes hospitalizados", emoji: "🏥" },
      { time: "9:00 am", activity: "Consultas en consultorio externo", emoji: "👨‍⚕️" },
      { time: "12:00 pm", activity: "Revisión de resultados de laboratorio", emoji: "🔬" },
      { time: "1:00 pm", activity: "Almuerzo rápido entre turnos", emoji: "🍽️" },
      { time: "2:00 pm", activity: "Procedimientos o cirugías programadas", emoji: "🏨" },
      { time: "4:00 pm", activity: "Actualización de historias clínicas", emoji: "📝" },
      { time: "6:00 pm", activity: "Interconsultas con especialistas", emoji: "📞" },
    ],
    universities: ["UNMSM", "UPCH (Cayetano)", "PUCP", "U. Lima", "UCSUR", "URP"],
    outlook: "Alta",
    duration: "7 años + especialidad",
    nowDoing: "Atendiendo a un paciente en consultorio o revisando resultados de exámenes.",
    scene: ["🏥", "🩺", "💊", "🔬", "🩻"],
    tools: ["Estetoscopio", "RX Digital", "Historia clínica", "Ecógrafo"],
  },
  {
    id: "derecho",
    title: "Derecho",
    area: "Derecho",
    emoji: "⚖️",
    color: "#b45309",
    lightBg: "#fffbeb",
    description:
      "Defiendes derechos, argumentas casos y das forma a la justicia. El derecho está en todo: empresas, familias, el Estado y la sociedad.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Argumentación", "Lectura crítica", "Negociación", "Ética", "Escritura"],
    skillRequirements: [
      { name: "Argumentación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Lectura crítica", requiredLevel: "intermedio", category: "academica" },
      { name: "Negociación", requiredLevel: "basico", category: "blanda" },
      { name: "Ética", requiredLevel: "intermedio", category: "blanda" },
      { name: "Escritura", requiredLevel: "intermedio", category: "academica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisas expedientes y jurisprudencia", emoji: "📚" },
      { time: "9:30 am", activity: "Reunión con cliente para estrategia legal", emoji: "🤝" },
      { time: "11:00 am", activity: "Redactas escritos, demandas o contratos", emoji: "✍️" },
      { time: "1:00 pm", activity: "Almuerzo y repaso de audios de audiencias", emoji: "🍱" },
      { time: "2:30 pm", activity: "Audiencia o diligencia en juzgado", emoji: "🏛️" },
      { time: "4:00 pm", activity: "Revisión de contratos para empresa cliente", emoji: "📄" },
      { time: "6:00 pm", activity: "Investigación jurídica para el caso del día siguiente", emoji: "🔍" },
    ],
    universities: ["PUCP", "UNMSM", "U. Lima", "UPC", "UP", "USMP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Redactando un escrito judicial o revisando contratos en tu computadora.",
    scene: ["⚖️", "📚", "🏛️", "📄", "🔍"],
    tools: ["El Peruano", "SREJ", "LexisNexis", "Word"],
  },
  {
    id: "administracion",
    title: "Administración",
    area: "Negocios",
    emoji: "📊",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description:
      "Líderas organizaciones, tomas decisiones estratégicas y haces que los equipos y recursos funcionen al máximo. La carrera más versátil del mundo de negocios.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Liderazgo", "Pensamiento estratégico", "Comunicación", "Análisis financiero", "Gestión de equipos"],
    skillRequirements: [
      { name: "Liderazgo", requiredLevel: "basico", category: "blanda" },
      { name: "Pensamiento estratégico", requiredLevel: "basico", category: "academica" },
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Análisis financiero", requiredLevel: "basico", category: "academica" },
      { name: "Gestión de equipos", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "8:30 am", activity: "Revisas KPIs y dashboard del negocio", emoji: "📈" },
      { time: "9:00 am", activity: "Reunión de alineación con el equipo gerencial", emoji: "🗣️" },
      { time: "10:30 am", activity: "Análisis de propuesta de nuevo proveedor", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo de trabajo con cliente clave", emoji: "🍽️" },
      { time: "2:30 pm", activity: "Presentación de resultados al directorio", emoji: "📊" },
      { time: "4:00 pm", activity: "Revisión del presupuesto trimestral", emoji: "💰" },
      { time: "5:30 pm", activity: "Networking en evento del sector", emoji: "🌐" },
    ],
    universities: ["PUCP", "U. Lima", "UPC", "UP", "ESAN", "USIL"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "En una reunión de estrategia, revisando métricas o cerrando un deal.",
    scene: ["📊", "💼", "🤝", "📈", "🌐"],
    tools: ["Excel", "SAP", "PowerBI", "Salesforce", "Slack"],
  },
  {
    id: "contabilidad",
    title: "Contabilidad",
    area: "Negocios",
    emoji: "🧾",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description:
      "Eres el guardián financiero de las empresas. Registras, analizas y reportas el estado económico real de una organización.",
    salary: "S/. 2,500 – 9,000",
    salaryMin: 2500,
    skills: ["Precisión", "Matemáticas", "Atención al detalle", "Normativa tributaria", "Análisis financiero"],
    skillRequirements: [
      { name: "Precisión", requiredLevel: "intermedio", category: "blanda" },
      { name: "Matemáticas", requiredLevel: "intermedio", category: "academica" },
      { name: "Atención al detalle", requiredLevel: "intermedio", category: "blanda" },
      { name: "Normativa tributaria", requiredLevel: "basico", category: "tecnica" },
      { name: "Análisis financiero", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Registro de operaciones contables del día anterior", emoji: "📒" },
      { time: "9:30 am", activity: "Declaración de impuestos o revisión SUNAT", emoji: "🏛️" },
      { time: "11:00 am", activity: "Conciliación bancaria y estados financieros", emoji: "🏦" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de noticias tributarias", emoji: "🍱" },
      { time: "2:00 pm", activity: "Auditoría interna de comprobantes", emoji: "🔍" },
      { time: "4:00 pm", activity: "Cierre contable mensual", emoji: "📊" },
      { time: "5:30 pm", activity: "Informe a gerencia sobre situación fiscal", emoji: "📑" },
    ],
    universities: ["PUCP", "UNMSM", "UPC", "USMP", "U. Continental", "UCV"],
    outlook: "Estable",
    duration: "5 años",
    nowDoing: "Analizando estados financieros o preparando declaraciones tributarias.",
    scene: ["🧾", "💰", "📊", "🏦", "🔢"],
    tools: ["CONCAR", "Excel", "SIRE SUNAT", "SAP", "PDT"],
  },
  {
    id: "ingenieria-civil",
    title: "Ingeniería Civil",
    area: "Ingeniería",
    emoji: "🏗️",
    color: "#dc2626",
    lightBg: "#fff1f1",
    description:
      "Construyes la infraestructura que sostiene al país: carreteras, puentes, edificios, represas. Tu trabajo dura generaciones.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Matemáticas", "Física", "Gestión de proyectos", "AutoCAD", "Liderazgo de obras"],
    skillRequirements: [
      { name: "Matemáticas", requiredLevel: "intermedio", category: "academica" },
      { name: "Física", requiredLevel: "intermedio", category: "academica" },
      { name: "Gestión de proyectos", requiredLevel: "basico", category: "blanda" },
      { name: "AutoCAD", requiredLevel: "basico", category: "tecnica" },
      { name: "Liderazgo de obras", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "7:00 am", activity: "Supervisión en obra — revisas avances del día", emoji: "👷" },
      { time: "9:00 am", activity: "Reunión con residente y maestros de obra", emoji: "🤝" },
      { time: "10:30 am", activity: "Diseño y revisión de planos en oficina técnica", emoji: "📐" },
      { time: "1:00 pm", activity: "Almuerzo en obra o en oficina", emoji: "🍱" },
      { time: "2:00 pm", activity: "Control de calidad de materiales", emoji: "🔩" },
      { time: "3:30 pm", activity: "Cálculo estructural con software", emoji: "🖥️" },
      { time: "5:00 pm", activity: "Informe de avance y reporte a cliente", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UNMSM", "UPC", "U. Piura", "UNSA"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "En obra supervisando o en la oficina calculando estructuras.",
    scene: ["🏗️", "👷", "📐", "🔩", "🏛️"],
    tools: ["AutoCAD", "ETABS", "SAP2000", "Revit", "S10"],
  },
  {
    id: "arquitectura",
    title: "Arquitectura y Urbanismo Ambiental",
    area: "Diseño",
    emoji: "🏛️",
    color: "#be185d",
    lightBg: "#fdf2f8",
    description:
      "Diseñas espacios que mejoran la vida de las personas. Combinas arte, ciencia y funcionalidad para crear desde una casa hasta una ciudad.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Creatividad", "Visión espacial", "AutoCAD", "Gestión de proyectos", "Dibujo técnico"],
    skillRequirements: [
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Visión espacial", requiredLevel: "basico", category: "blanda" },
      { name: "AutoCAD", requiredLevel: "basico", category: "tecnica" },
      { name: "Gestión de proyectos", requiredLevel: "basico", category: "blanda" },
      { name: "Dibujo técnico", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas referencias e inspiración para proyecto", emoji: "🖼️" },
      { time: "10:00 am", activity: "Dibujas bocetos y esquemas de distribución", emoji: "✏️" },
      { time: "12:00 pm", activity: "Presentación de anteproyecto a cliente", emoji: "🗣️" },
      { time: "1:00 pm", activity: "Almuerzo y recorrido por referencias urbanas", emoji: "🏙️" },
      { time: "2:30 pm", activity: "Modelado 3D del proyecto en Revit o SketchUp", emoji: "🖥️" },
      { time: "4:30 pm", activity: "Coordinación con ingenieros estructurales", emoji: "🤝" },
      { time: "6:00 pm", activity: "Renderizas imágenes del proyecto finalizado", emoji: "✨" },
    ],
    universities: ["PUCP", "UNI", "U. Lima", "UPC", "Ricardo Palma", "USIL"],
    outlook: "Media",
    duration: "5-6 años",
    nowDoing: "Diseñando planos o modelando en 3D con música de fondo.",
    scene: ["🏛️", "✏️", "📐", "🖥️", "🏙️"],
    tools: ["AutoCAD", "Revit", "SketchUp", "Lumion", "Photoshop"],
  },
  {
    id: "psicologia",
    title: "Psicología",
    area: "Salud",
    emoji: "🧠",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description:
      "Entiendes el comportamiento humano desde adentro. Ayudas a personas, empresas y comunidades a funcionar mejor emocionalmente.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Empatía", "Escucha activa", "Observación", "Comunicación", "Neutralidad emocional"],
    skillRequirements: [
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Escucha activa", requiredLevel: "intermedio", category: "blanda" },
      { name: "Observación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Neutralidad emocional", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas notas de sesiones anteriores", emoji: "📓" },
      { time: "9:30 am", activity: "Sesión de terapia individual (50 min)", emoji: "💬" },
      { time: "11:00 am", activity: "Segunda sesión con paciente adolescente", emoji: "🧑" },
      { time: "1:00 pm", activity: "Almuerzo y supervisión con colega", emoji: "🍱" },
      { time: "2:30 pm", activity: "Sesión de terapia de pareja", emoji: "👫" },
      { time: "4:00 pm", activity: "Redacción de informes psicológicos", emoji: "📝" },
      { time: "5:30 pm", activity: "Actualización en nuevas técnicas terapéuticas", emoji: "📚" },
    ],
    universities: ["PUCP", "UNMSM", "U. Lima", "UPC", "USMP", "UNFV"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "En una sesión de terapia o redactando informes psicológicos.",
    scene: ["🧠", "💬", "🛋️", "📓", "🌱"],
    tools: ["DSM-5", "Tests psicométricos", "Plataformas de teleconsulta"],
  },
  {
    id: "marketing",
    title: "Marketing y Gestión de Medios",
    area: "Negocios",
    emoji: "📣",
    color: "#ea580c",
    lightBg: "#fff7ed",
    description:
      "Conectas marcas con personas. Diseñas estrategias, creas contenido y usas datos para que los productos lleguen al corazón del consumidor.",
    salary: "S/. 2,500 – 10,000",
    salaryMin: 2500,
    skills: ["Creatividad", "Análisis de datos", "Storytelling", "Social media", "Visión de tendencias"],
    skillRequirements: [
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Análisis de datos", requiredLevel: "basico", category: "tecnica" },
      { name: "Storytelling", requiredLevel: "basico", category: "blanda" },
      { name: "Social media", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Visión de tendencias", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas métricas de campañas activas", emoji: "📊" },
      { time: "9:30 am", activity: "Brainstorming de ideas para nuevo lanzamiento", emoji: "💡" },
      { time: "11:00 am", activity: "Aprobación de piezas creativas con el equipo", emoji: "🎨" },
      { time: "1:00 pm", activity: "Almuerzo revisando tendencias en TikTok", emoji: "📱" },
      { time: "2:30 pm", activity: "Reunión con influencers o agencia creativa", emoji: "🤝" },
      { time: "4:00 pm", activity: "Análisis de resultados de campaña Google Ads", emoji: "📈" },
      { time: "5:30 pm", activity: "Presentación de estrategia mensual", emoji: "🎯" },
    ],
    universities: ["U. Lima", "PUCP", "UPC", "USIL", "UP", "ESAN"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Revisando métricas de campañas o creando contenido para redes sociales.",
    scene: ["📣", "📊", "📱", "🎨", "🎯"],
    tools: ["Meta Ads", "Google Analytics", "Canva", "HubSpot", "Notion"],
  },
  {
    id: "diseno-ux",
    title: "Diseño UX/UI",
    area: "Diseño",
    emoji: "🎨",
    color: "#db2777",
    lightBg: "#fdf2f8",
    description:
      "Haces que la tecnología sea intuitiva y bella. Diseñas la experiencia que millones de personas tienen al usar apps y plataformas digitales.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Creatividad", "Empatía con el usuario", "Figma", "Pensamiento de diseño", "Prototipado"],
    skillRequirements: [
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Empatía con el usuario", requiredLevel: "intermedio", category: "blanda" },
      { name: "Figma", requiredLevel: "basico", category: "tecnica" },
      { name: "Pensamiento de diseño", requiredLevel: "basico", category: "blanda" },
      { name: "Prototipado", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas feedback de usuarios de la semana", emoji: "💬" },
      { time: "9:30 am", activity: "Sesión de diseño en Figma — wireframes", emoji: "🖌️" },
      { time: "11:30 am", activity: "User testing con 3 personas reales", emoji: "👥" },
      { time: "1:00 pm", activity: "Almuerzo y revisas Dribbble para inspiración", emoji: "🍱" },
      { time: "2:30 pm", activity: "Refinamiento del design system", emoji: "✨" },
      { time: "4:00 pm", activity: "Handoff a desarrolladores con especificaciones", emoji: "🤝" },
      { time: "5:30 pm", activity: "Revisión de prototipo interactivo", emoji: "📱" },
    ],
    universities: ["PUCP", "UPC", "ISIL", "Toulouse Lautrec", "U. Lima", "UTEC"],
    outlook: "Alta",
    duration: "4-5 años",
    nowDoing: "Diseñando interfaces en Figma o haciendo pruebas con usuarios reales.",
    scene: ["🎨", "🖌️", "📱", "💻", "✨"],
    tools: ["Figma", "Adobe XD", "Illustrator", "Maze", "Notion"],
  },
  {
    id: "enfermeria",
    title: "Enfermería",
    area: "Salud",
    emoji: "💉",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description:
      "Cuidas a las personas en sus momentos más delicados. Eres el contacto humano más constante en cualquier sistema de salud.",
    salary: "S/. 2,500 – 7,000",
    salaryMin: 2500,
    skills: ["Empatía", "Precisión", "Trabajo bajo presión", "Técnicas clínicas", "Comunicación"],
    skillRequirements: [
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Precisión", requiredLevel: "intermedio", category: "blanda" },
      { name: "Trabajo bajo presión", requiredLevel: "basico", category: "blanda" },
      { name: "Técnicas clínicas", requiredLevel: "basico", category: "tecnica" },
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "7:00 am", activity: "Recepción de turno y revisión de pacientes", emoji: "📋" },
      { time: "8:00 am", activity: "Administración de medicamentos", emoji: "💊" },
      { time: "10:00 am", activity: "Toma de signos vitales y registros", emoji: "📊" },
      { time: "1:00 pm", activity: "Almuerzo entre turnos", emoji: "🍱" },
      { time: "2:00 pm", activity: "Curación de heridas y procedimientos", emoji: "🩹" },
      { time: "4:00 pm", activity: "Educación al paciente y familia", emoji: "👨‍👩‍👧" },
      { time: "6:00 pm", activity: "Reporte de turno al equipo médico", emoji: "📝" },
    ],
    universities: ["UNMSM", "UPCH", "PUCP", "URP", "USMP", "U. Continental"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Atendiendo pacientes en sala o monitoreando signos vitales.",
    scene: ["💉", "🏥", "💊", "🩹", "❤️"],
    tools: ["Monitor de signos vitales", "Glucómetro", "Sistema HIS"],
  },
  {
    id: "ingenieria-industrial",
    title: "Ingeniería Industrial",
    area: "Ingeniería",
    emoji: "⚙️",
    color: "#475569",
    lightBg: "#f8fafc",
    description:
      "Optimizas sistemas de producción, cadenas de suministro y procesos empresariales. Haces que las cosas funcionen mejor, más rápido y más barato.",
    salary: "S/. 3,500 – 12,000",
    salaryMin: 3500,
    skills: ["Análisis de procesos", "Estadística", "Liderazgo", "Calidad", "Logística"],
    skillRequirements: [
      { name: "Análisis de procesos", requiredLevel: "basico", category: "tecnica" },
      { name: "Estadística", requiredLevel: "intermedio", category: "academica" },
      { name: "Liderazgo", requiredLevel: "basico", category: "blanda" },
      { name: "Calidad", requiredLevel: "basico", category: "tecnica" },
      { name: "Logística", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisión de indicadores de producción", emoji: "📊" },
      { time: "9:00 am", activity: "Recorrido por planta para identificar cuellos de botella", emoji: "🏭" },
      { time: "10:30 am", activity: "Análisis de datos y propuesta de mejora", emoji: "📈" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de proveedores", emoji: "🍱" },
      { time: "2:00 pm", activity: "Implementación de metodología Lean", emoji: "⚙️" },
      { time: "4:00 pm", activity: "Reunión con gerencia de operaciones", emoji: "🤝" },
      { time: "5:30 pm", activity: "Informe de eficiencia semanal", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "U. Lima", "UPC", "UNMSM", "U. Piura"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Analizando procesos productivos o implementando mejoras en planta.",
    scene: ["⚙️", "🏭", "📊", "📈", "🔧"],
    tools: ["Minitab", "AutoCAD", "SAP", "Excel avanzado", "Arena Simulation"],
  },
  {
    id: "economia",
    title: "Economía y Finanzas",
    area: "Negocios",
    emoji: "💹",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description:
      "Analizas cómo funciona el sistema económico a nivel macro y micro. Informas decisiones de gobierno, banca central, empresas y organismos internacionales.",
    salary: "S/. 3,500 – 14,000",
    salaryMin: 3500,
    skills: ["Estadística", "Econometría", "Análisis de datos", "Pensamiento crítico", "Programación (R/Python)"],
    skillRequirements: [
      { name: "Estadística", requiredLevel: "intermedio", category: "academica" },
      { name: "Econometría", requiredLevel: "basico", category: "academica" },
      { name: "Análisis de datos", requiredLevel: "basico", category: "tecnica" },
      { name: "Pensamiento crítico", requiredLevel: "intermedio", category: "academica" },
      { name: "Programación (R/Python)", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas reportes del BCRP e INEI", emoji: "📰" },
      { time: "10:00 am", activity: "Modelado econométrico con datos de mercado", emoji: "📊" },
      { time: "12:00 pm", activity: "Reunión con equipo de research", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de noticias económicas", emoji: "🍱" },
      { time: "2:30 pm", activity: "Redacción de informe de coyuntura económica", emoji: "✍️" },
      { time: "4:00 pm", activity: "Presentación de análisis a directivos", emoji: "📈" },
      { time: "5:30 pm", activity: "Actualización de modelos de proyección", emoji: "💹" },
    ],
    universities: ["PUCP", "U. Lima", "UNMSM", "UP", "ESAN", "UPC"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Modelando proyecciones económicas o redactando un informe de coyuntura.",
    scene: ["💹", "📊", "📈", "🏦", "🌍"],
    tools: ["Stata", "R", "Python", "Bloomberg", "EViews"],
  },
  {
    id: "gastronomia",
    title: "Gastronomía",
    area: "Gastronomía",
    emoji: "👨‍🍳",
    color: "#dc2626",
    lightBg: "#fff1f1",
    description:
      "Llevas la cocina peruana al mundo. Creas experiencias culinarias únicas que combinan técnica, creatividad y cultura. Perú es el país de la gastronomía latinoamericana.",
    salary: "S/. 2,000 – 10,000",
    salaryMin: 2000,
    skills: ["Creatividad", "Paladar desarrollado", "Resistencia física", "Gestión de cocina", "Pasión"],
    skillRequirements: [
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Paladar desarrollado", requiredLevel: "basico", category: "blanda" },
      { name: "Resistencia física", requiredLevel: "intermedio", category: "blanda" },
      { name: "Gestión de cocina", requiredLevel: "basico", category: "tecnica" },
      { name: "Pasión", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisas mise en place y lista de insumos", emoji: "📋" },
      { time: "9:00 am", activity: "Preparación de fondos, salsas y bases", emoji: "🍲" },
      { time: "11:00 am", activity: "Degustación y ajuste de nuevos platos", emoji: "🍽️" },
      { time: "12:00 pm", activity: "Coordinación con brigada para el servicio", emoji: "👨‍🍳" },
      { time: "1:00 pm", activity: "Servicio del almuerzo — cocina a full velocidad", emoji: "🔥" },
      { time: "3:00 pm", activity: "Limpieza y preparación para servicio de noche", emoji: "🧹" },
      { time: "6:00 pm", activity: "Servicio de cena — tu mejor momento del día", emoji: "✨" },
    ],
    universities: ["Le Cordon Bleu", "USIL", "ISG", "D'Gallia", "UTP", "UNMSM"],
    outlook: "Alta",
    duration: "3-5 años",
    nowDoing: "En cocina preparando mise en place o creando un nuevo plato.",
    scene: ["👨‍🍳", "🍳", "🌶️", "🐟", "✨"],
    tools: ["Thermomix", "Sous vide", "Pacojet", "Cuchillos japoneses"],
  },
  {
    id: "periodismo",
    title: "Periodismo & Comunicación",
    area: "Humanidades",
    emoji: "📰",
    color: "#1d4ed8",
    lightBg: "#eff6ff",
    description:
      "Informas, investigas y haces que la sociedad rinda cuentas. El periodismo es el cuarto poder — esencial para cualquier democracia.",
    salary: "S/. 2,000 – 8,000",
    salaryMin: 2000,
    skills: ["Escritura", "Investigación", "Entrevistas", "Edición de video", "Redes sociales"],
    skillRequirements: [
      { name: "Escritura", requiredLevel: "intermedio", category: "academica" },
      { name: "Investigación", requiredLevel: "intermedio", category: "academica" },
      { name: "Entrevistas", requiredLevel: "basico", category: "blanda" },
      { name: "Edición de video", requiredLevel: "basico", category: "tecnica" },
      { name: "Redes sociales", requiredLevel: "intermedio", category: "tecnica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisas agenda de noticias y conferencias", emoji: "📰" },
      { time: "9:00 am", activity: "Reportería — entrevistas en campo", emoji: "🎤" },
      { time: "11:00 am", activity: "Redacción de nota o crónica del día", emoji: "✍️" },
      { time: "1:00 pm", activity: "Almuerzo y monitoreo de redes", emoji: "📱" },
      { time: "2:30 pm", activity: "Edición de video o audio para multiplataforma", emoji: "🎬" },
      { time: "4:00 pm", activity: "Publicación y seguimiento en tiempo real", emoji: "🚀" },
      { time: "6:00 pm", activity: "Cobertura de evento de última hora", emoji: "🔴" },
    ],
    universities: ["PUCP", "U. Lima", "UNMSM", "UPC", "UP", "USMP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "En campo haciendo reportería o redactando una nota para su medio.",
    scene: ["📰", "🎤", "📡", "✍️", "📸"],
    tools: ["Adobe Premiere", "Audacity", "WordPress", "Redes sociales"],
  },
  {
    id: "ingenieria-minas",
    title: "Ingeniería de Minas",
    area: "Ingeniería",
    emoji: "⛏️",
    color: "#92400e",
    lightBg: "#fffbeb",
    description:
      "Extraes los minerales que hacen posible la tecnología moderna. Perú es uno de los mayores productores de cobre, oro y zinc del mundo.",
    salary: "S/. 5,000 – 18,000",
    salaryMin: 5000,
    skills: ["Geología", "Explosivos", "Seguridad minera", "Gestión ambiental", "Liderazgo"],
    skillRequirements: [
      { name: "Geología", requiredLevel: "basico", category: "academica" },
      { name: "Explosivos", requiredLevel: "basico", category: "tecnica" },
      { name: "Seguridad minera", requiredLevel: "basico", category: "tecnica" },
      { name: "Gestión ambiental", requiredLevel: "basico", category: "tecnica" },
      { name: "Liderazgo", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "6:00 am", activity: "Briefing de seguridad antes de bajar a mina", emoji: "⛑️" },
      { time: "7:00 am", activity: "Supervisión de tajo abierto o galería", emoji: "⛏️" },
      { time: "9:00 am", activity: "Control de perforación y voladura", emoji: "💥" },
      { time: "12:00 pm", activity: "Almuerzo en campamento minero", emoji: "🍽️" },
      { time: "1:30 pm", activity: "Análisis geológico y planeamiento de avance", emoji: "🗺️" },
      { time: "3:00 pm", activity: "Reunión de seguridad y reporte de incidentes", emoji: "📋" },
      { time: "5:00 pm", activity: "Cierre de guardia y relevo de turno", emoji: "🔄" },
    ],
    universities: ["UNI", "UNMSM", "U. Nacional de Ingeniería", "UNSA", "UNDAC", "U. Continental"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Supervisando operaciones en tajo o analizando muestras geológicas.",
    scene: ["⛏️", "⛰️", "💎", "⛑️", "🗺️"],
    tools: ["Vulcan", "Surpac", "AutoCAD", "GPS minero"],
  },
  {
    id: "odontologia",
    title: "Odontología",
    area: "Salud",
    emoji: "🦷",
    color: "#0284c7",
    lightBg: "#f0f9ff",
    description:
      "Cuidas la salud bucal de las personas. Más que dientes, trabajas con la confianza y autoestima de tus pacientes.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Precisión manual", "Empatía", "Anatomía", "Técnica clínica", "Paciencia"],
    skillRequirements: [
      { name: "Precisión manual", requiredLevel: "intermedio", category: "blanda" },
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Anatomía", requiredLevel: "intermedio", category: "academica" },
      { name: "Técnica clínica", requiredLevel: "basico", category: "tecnica" },
      { name: "Paciencia", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas agenda de pacientes del día", emoji: "📅" },
      { time: "9:30 am", activity: "Primera consulta — diagnóstico y plan de tratamiento", emoji: "🔍" },
      { time: "11:00 am", activity: "Procedimiento de endodoncia o extracción", emoji: "🦷" },
      { time: "1:00 pm", activity: "Almuerzo y descanso entre turnos", emoji: "🍱" },
      { time: "2:00 pm", activity: "Sesión de ortodoncia — ajuste de brackets", emoji: "✨" },
      { time: "3:30 pm", activity: "Colocación de carillas o blanqueamiento", emoji: "😁" },
      { time: "5:00 pm", activity: "Revisión de resultados de radiografías", emoji: "🩻" },
    ],
    universities: ["UNMSM", "UPCH", "PUCP", "UPC", "U. Continental", "USMP"],
    outlook: "Alta",
    duration: "6 años",
    nowDoing: "Atendiendo pacientes en tu consultorio o realizando un procedimiento dental.",
    scene: ["🦷", "😁", "🔬", "💉", "✨"],
    tools: ["Rx periapical", "Scanner intraoral", "Ultrasonido dental"],
  },
  {
    id: "ingenieria-ambiental",
    title: "Ingeniería Ambiental",
    area: "Ingeniería",
    emoji: "🌿",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description:
      "Proteges el planeta mientras las empresas crecen. Diseñas soluciones para reducir el impacto ambiental de industrias, ciudades y proyectos.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Química", "Biología", "Legislación ambiental", "SIG", "Gestión de residuos"],
    skillRequirements: [
      { name: "Química", requiredLevel: "intermedio", category: "academica" },
      { name: "Biología", requiredLevel: "intermedio", category: "academica" },
      { name: "Legislación ambiental", requiredLevel: "basico", category: "tecnica" },
      { name: "SIG", requiredLevel: "basico", category: "tecnica" },
      { name: "Gestión de residuos", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Monitoreo de calidad de aire y agua", emoji: "🌊" },
      { time: "9:30 am", activity: "Elaboración de Estudio de Impacto Ambiental", emoji: "📝" },
      { time: "11:00 am", activity: "Visita a planta para auditoría ambiental", emoji: "🏭" },
      { time: "1:00 pm", activity: "Almuerzo al aire libre — parte del trabajo", emoji: "🌳" },
      { time: "2:30 pm", activity: "Análisis de muestras en laboratorio", emoji: "🔬" },
      { time: "4:00 pm", activity: "Presentación de resultados a empresa cliente", emoji: "📊" },
      { time: "5:30 pm", activity: "Actualización de registros OEFA/OSINERGMIN", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UNMSM", "U. Agraria La Molina", "UNSA", "UCV"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Realizando monitoreos ambientales o elaborando estudios de impacto.",
    scene: ["🌿", "🌊", "♻️", "🌍", "🔬"],
    tools: ["ArcGIS", "AutoCAD", "ENVI", "R", "Equipos de muestreo"],
  },
  {
    id: "educacion",
    title: "Educación & Pedagogía",
    area: "Educación",
    emoji: "📚",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description:
      "Formas a las generaciones que cambiarán el país. Los mejores docentes no enseñan asignaturas — enseñan a pensar.",
    salary: "S/. 2,000 – 7,000",
    salaryMin: 2000,
    skills: ["Comunicación", "Empatía", "Didáctica", "Creatividad", "Paciencia"],
    skillRequirements: [
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Didáctica", requiredLevel: "basico", category: "academica" },
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Paciencia", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "7:30 am", activity: "Preparas materiales y sesión del día", emoji: "📋" },
      { time: "8:00 am", activity: "Primera clase del día — dinámica de inicio", emoji: "👋" },
      { time: "10:00 am", activity: "Clase con el grupo más desafiante — tu favorito", emoji: "🌟" },
      { time: "12:00 pm", activity: "Almuerzo y revisión de tareas", emoji: "🍱" },
      { time: "1:00 pm", activity: "Tutoría personalizada con alumno que necesita apoyo", emoji: "🤝" },
      { time: "3:00 pm", activity: "Reunión de padres de familia", emoji: "👨‍👩‍👧" },
      { time: "4:30 pm", activity: "Planificación curricular para la semana", emoji: "📅" },
    ],
    universities: ["PUCP", "UNMSM", "UNE La Cantuta", "U. Privada del Norte", "USIL", "UCV"],
    outlook: "Estable",
    duration: "5 años",
    nowDoing: "Preparando una clase o en el aula con sus estudiantes.",
    scene: ["📚", "✏️", "🏫", "🌟", "🤝"],
    tools: ["Google Classroom", "Canva", "Kahoot", "Moodle", "Pizarra digital"],
  },
  {
    id: "nutricion",
    title: "Nutrición y Dietética",
    area: "Salud",
    emoji: "🥗",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description:
      "Transformas la relación de las personas con su alimentación. Trabajas en hospitales, clínicas, empresas deportivas y consultorios propios.",
    salary: "S/. 2,000 – 7,000",
    salaryMin: 2000,
    skills: ["Bioquímica", "Anatomía", "Empatía", "Elaboración de dietas", "Educación alimentaria"],
    skillRequirements: [
      { name: "Bioquímica", requiredLevel: "intermedio", category: "academica" },
      { name: "Anatomía", requiredLevel: "intermedio", category: "academica" },
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Elaboración de dietas", requiredLevel: "basico", category: "tecnica" },
      { name: "Educación alimentaria", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Consulta inicial con nuevo paciente — anamnesis", emoji: "📋" },
      { time: "10:00 am", activity: "Análisis de composición corporal", emoji: "⚖️" },
      { time: "11:00 am", activity: "Elaboración de plan nutricional personalizado", emoji: "🥗" },
      { time: "1:00 pm", activity: "Almuerzo saludable — practicas lo que predicas", emoji: "🍎" },
      { time: "2:00 pm", activity: "Seguimiento de paciente crónico", emoji: "📊" },
      { time: "3:30 pm", activity: "Taller de educación alimentaria en empresa", emoji: "👨‍🏫" },
      { time: "5:00 pm", activity: "Actualización de protocolos y literatura científica", emoji: "📚" },
    ],
    universities: ["UNMSM", "UPCH", "UNI", "U. Agraria La Molina", "URP", "USMP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Atendiendo consultas o elaborando planes nutricionales personalizados.",
    scene: ["🥗", "🍎", "⚖️", "📊", "💪"],
    tools: ["Software de análisis nutricional", "Báscula de bioimpedancia"],
  },
  {
    id: "turismo",
    title: "Turismo Sostenible y Hotelería",
    area: "Humanidades",
    emoji: "✈️",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description:
      "Muestras lo mejor del Perú al mundo. Diseñas experiencias de viaje únicas y gestionas destinos turísticos que generan valor para las comunidades.",
    salary: "S/. 2,000 – 8,000",
    salaryMin: 2000,
    skills: ["Idiomas", "Organización", "Servicio al cliente", "Cultura general", "Gestión de crisis"],
    skillRequirements: [
      { name: "Idiomas", requiredLevel: "intermedio", category: "academica" },
      { name: "Organización", requiredLevel: "intermedio", category: "blanda" },
      { name: "Servicio al cliente", requiredLevel: "intermedio", category: "blanda" },
      { name: "Cultura general", requiredLevel: "intermedio", category: "academica" },
      { name: "Gestión de crisis", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Check-in de grupos y coordinación con guías", emoji: "🗺️" },
      { time: "9:30 am", activity: "Tour por Miraflores, Centro Histórico o Cusco", emoji: "🏛️" },
      { time: "12:00 pm", activity: "Almuerzo gastronómico con turistas", emoji: "🍽️" },
      { time: "2:00 pm", activity: "Coordinación logística para el día siguiente", emoji: "📋" },
      { time: "3:30 pm", activity: "Venta de paquetes a nuevos clientes", emoji: "💼" },
      { time: "5:00 pm", activity: "Reporte de operaciones y revisión de reservas", emoji: "📊" },
      { time: "7:00 pm", activity: "Cena de bienvenida con grupo internacional", emoji: "🌍" },
    ],
    universities: ["USIL", "U. San Martín", "U. Le Cordon Bleu", "UPC", "UNMSM", "UP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Guiando turistas por Perú o coordinando el siguiente viaje del grupo.",
    scene: ["✈️", "🗺️", "🏛️", "🌍", "📸"],
    tools: ["Amadeus GDS", "Opera PMS", "TripAdvisor", "Booking"],
  },
  {
    id: "relaciones-internacionales",
    title: "Relaciones Internacionales",
    area: "Humanidades",
    emoji: "🌐",
    color: "#1d4ed8",
    lightBg: "#eff6ff",
    description:
      "Navegas el sistema internacional: diplomacia, comercio exterior, organismos multilaterales y política exterior. Representas al país o a organizaciones globales.",
    salary: "S/. 3,000 – 12,000",
    salaryMin: 3000,
    skills: ["Idiomas (mínimo 2)", "Análisis político", "Negociación", "Protocolo", "Geopolítica"],
    skillRequirements: [
      { name: "Idiomas (mínimo 2)", requiredLevel: "intermedio", category: "academica" },
      { name: "Análisis político", requiredLevel: "intermedio", category: "academica" },
      { name: "Negociación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Protocolo", requiredLevel: "basico", category: "tecnica" },
      { name: "Geopolítica", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas cable diplomático y noticias internacionales", emoji: "📰" },
      { time: "10:00 am", activity: "Reunión con delegación extranjera", emoji: "🤝" },
      { time: "12:00 pm", activity: "Almuerzo protocolar con diplomáticos", emoji: "🍽️" },
      { time: "2:00 pm", activity: "Redacción de notas diplomáticas o informes", emoji: "✍️" },
      { time: "4:00 pm", activity: "Seguimiento de negociaciones comerciales bilaterales", emoji: "📋" },
      { time: "5:30 pm", activity: "Evento de la embajada o cónsul", emoji: "🎉" },
      { time: "7:00 pm", activity: "Estudio de idioma o actualización geopolítica", emoji: "📚" },
    ],
    universities: ["PUCP", "UP", "U. Lima", "USMP", "UNMSM", "UPC"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "En negociaciones internacionales o redactando informes de política exterior.",
    scene: ["🌐", "🤝", "🏛️", "✈️", "📋"],
    tools: ["Idiomas", "Protocolo diplomático", "Derecho Internacional"],
  },
  {
    id: "veterinaria",
    title: "Medicina Veterinaria",
    area: "Salud",
    emoji: "🐾",
    color: "#d97706",
    lightBg: "#fffbeb",
    description:
      "Cuidas la salud animal — desde mascotas hasta ganado y fauna silvestre. En Perú tienes enorme campo en ganadería, acuicultura y conservación.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Empatía animal", "Cirugía", "Diagnóstico clínico", "Resistencia", "Farmacología"],
    skillRequirements: [
      { name: "Empatía animal", requiredLevel: "intermedio", category: "blanda" },
      { name: "Cirugía", requiredLevel: "basico", category: "tecnica" },
      { name: "Diagnóstico clínico", requiredLevel: "basico", category: "tecnica" },
      { name: "Resistencia", requiredLevel: "intermedio", category: "blanda" },
      { name: "Farmacología", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Atención de urgencias de la mañana", emoji: "🚨" },
      { time: "9:30 am", activity: "Consultas programadas — perros, gatos, exóticos", emoji: "🐕" },
      { time: "11:00 am", activity: "Cirugía de esterilización o procedimiento mayor", emoji: "🏥" },
      { time: "1:00 pm", activity: "Almuerzo con el equipo veterinario", emoji: "🍱" },
      { time: "2:30 pm", activity: "Vacunación y controles de rutina", emoji: "💉" },
      { time: "4:00 pm", activity: "Análisis de resultados de laboratorio", emoji: "🔬" },
      { time: "5:30 pm", activity: "Visita a granja o establo para chequeo de ganado", emoji: "🐄" },
    ],
    universities: ["UNMSM", "UPCH", "U. Cayetano Heredia", "UNA Puno", "UNSA", "UCV"],
    outlook: "Alta",
    duration: "5-6 años",
    nowDoing: "Atendiendo consultas o en quirófano realizando una cirugía.",
    scene: ["🐾", "🐕", "🏥", "💉", "🔬"],
    tools: ["Ecógrafo portátil", "Rx digital", "Laboratorio clínico"],
  },
  {
    id: "administracion-negocios-internacionales",
    title: "Administración y Negocios Internacionales",
    area: "Negocios",
    emoji: "🌍",
    color: "#2563eb",
    lightBg: "#eff6ff",
    description: "Gestionas negocios globales, estrategias de exportación e importación, y relaciones comerciales internacionales. Conectas empresas peruanas con mercados mundiales.",
    salary: "S/. 3,500 – 12,000",
    salaryMin: 3500,
    skills: ["Negociación internacional", "Idiomas", "Logística global", "Análisis de mercados", "Comercio exterior"],
    skillRequirements: [
      { name: "Negociación internacional", requiredLevel: "intermedio", category: "blanda" },
      { name: "Idiomas", requiredLevel: "intermedio", category: "academica" },
      { name: "Logística global", requiredLevel: "basico", category: "tecnica" },
      { name: "Análisis de mercados", requiredLevel: "basico", category: "academica" },
      { name: "Comercio exterior", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas cotizaciones internacionales y acuerdos comerciales", emoji: "📊" },
      { time: "10:30 am", activity: "Negociación con proveedor extranjero por videollamada", emoji: "🤝" },
      { time: "12:00 pm", activity: "Coordinación de logística de exportación", emoji: "📦" },
      { time: "1:00 pm", activity: "Almuerzo con delegación comercial", emoji: "🍽️" },
      { time: "2:30 pm", activity: "Análisis de aranceles y regulaciones aduaneras", emoji: "📋" },
      { time: "4:00 pm", activity: "Redacción de contratos internacionales", emoji: "✍️" },
      { time: "5:30 pm", activity: "Reporte de indicadores de comercio exterior", emoji: "📈" },
    ],
    universities: ["USIL", "PUCP", "UP", "U. Lima", "ESAN", "UPC"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Gestionando operaciones de comercio exterior o negociando con socios internacionales.",
    scene: ["🌍", "📦", "🤝", "✈️", "📊"],
    tools: ["SIGAD", "VUCE", "Excel", "Salesforce", "Idiomas"],
  },
  {
    id: "biologia-marina",
    title: "Biología Marina",
    area: "Ciencias",
    emoji: "🐠",
    color: "#0d9488",
    lightBg: "#f0fdfa",
    description: "Estudias los ecosistemas marinos y la vida en el océano. Investigas especies marinas, conservación de hábitats y el impacto del cambio climático en el mar peruano.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Observación científica", "Buceo", "Análisis de laboratorio", "Biología molecular", "Estadística"],
    skillRequirements: [
      { name: "Observación científica", requiredLevel: "intermedio", category: "academica" },
      { name: "Buceo", requiredLevel: "basico", category: "tecnica" },
      { name: "Análisis de laboratorio", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Biología molecular", requiredLevel: "basico", category: "academica" },
      { name: "Estadística", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "6:00 am", activity: "Toma de muestras en campo — costa o embarcación", emoji: "🌊" },
      { time: "9:00 am", activity: "Análisis de muestras en laboratorio", emoji: "🔬" },
      { time: "11:00 am", activity: "Registro y clasificación de especies", emoji: "📝" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de literatura científica", emoji: "🍱" },
      { time: "2:30 pm", activity: "Monitoreo de parámetros oceanográficos", emoji: "🌡️" },
      { time: "4:00 pm", activity: "Redacción de informes de investigación", emoji: "✍️" },
      { time: "5:30 pm", activity: "Reunión con equipo de conservación marina", emoji: "🤝" },
    ],
    universities: ["UNMSM", "U. Agraria La Molina", "UNI", "U. Nacional del Callao", "UCSUR"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "En laboratorio analizando muestras marinas o en campo realizando monitoreo.",
    scene: ["🐠", "🌊", "🔬", "🐚", "🌅"],
    tools: ["Microscopio", "SIG", "R", "Equipos de buceo", "GPS"],
  },
  {
    id: "ciencia-computacion",
    title: "Ciencia de la Computación",
    area: "Tecnología",
    emoji: "🖥️",
    color: "#6d28d9",
    lightBg: "#f5f3ff",
    description: "Investigas los fundamentos teóricos de la computación: algoritmos, inteligencia artificial, teorías de computación. Creas el futuro de la tecnología desde sus bases matemáticas.",
    salary: "S/. 5,000 – 18,000",
    salaryMin: 5000,
    skills: ["Matemáticas", "Algoritmos", "Programación", "Pensamiento abstracto", "Investigación"],
    skillRequirements: [
      { name: "Matemáticas", requiredLevel: "avanzado", category: "academica" },
      { name: "Algoritmos", requiredLevel: "intermedio", category: "academica" },
      { name: "Programación", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Pensamiento abstracto", requiredLevel: "intermedio", category: "blanda" },
      { name: "Investigación", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisas papers académicos y avances del campo", emoji: "📄" },
      { time: "10:00 am", activity: "Implementación de nuevo algoritmo", emoji: "⌨️" },
      { time: "12:00 pm", activity: "Discusión con grupo de investigación", emoji: "🗣️" },
      { time: "1:00 pm", activity: "Almuerzo y coding challenge", emoji: "🍱" },
      { time: "2:30 pm", activity: "Entrenamiento de modelo de IA", emoji: "🤖" },
      { time: "4:00 pm", activity: "Escritura de paper o documentación técnica", emoji: "✍️" },
      { time: "5:30 pm", activity: "Revisión de código abierto en GitHub", emoji: "🔍" },
    ],
    universities: ["UNI", "UTEC", "PUCP", "UNMSM", "USMP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Desarrollando algoritmos o entrenando modelos de machine learning.",
    scene: ["🖥️", "🤖", "📊", "⌨️", "🧮"],
    tools: ["Python", "C++", "TensorFlow", "LaTeX", "Linux"],
  },
  {
    id: "ciencias-comunicacion",
    title: "Ciencias de la Comunicación",
    area: "Humanidades",
    emoji: "🎙️",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description: "Analizas y creas mensajes para medios masivos. Trabajas en prensa, radio, televisión, medios digitales y comunicación corporativa. El poder de la información en tus manos.",
    salary: "S/. 2,000 – 7,000",
    salaryMin: 2000,
    skills: ["Redacción", "Comunicación verbal", "Edición multimedia", "Investigación", "Creatividad"],
    skillRequirements: [
      { name: "Redacción", requiredLevel: "intermedio", category: "academica" },
      { name: "Comunicación verbal", requiredLevel: "intermedio", category: "blanda" },
      { name: "Edición multimedia", requiredLevel: "basico", category: "tecnica" },
      { name: "Investigación", requiredLevel: "basico", category: "academica" },
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisión de agenda informativa del día", emoji: "📰" },
      { time: "9:00 am", activity: "Cobertura de conferencia o evento", emoji: "🎤" },
      { time: "11:00 am", activity: "Redacción de nota periodística", emoji: "✍️" },
      { time: "1:00 pm", activity: "Almuerzo y monitoreo de redes sociales", emoji: "📱" },
      { time: "2:30 pm", activity: "Edición de video o audio para plataformas", emoji: "🎬" },
      { time: "4:00 pm", activity: "Entrevista con fuente informativa", emoji: "🎙️" },
      { time: "5:30 pm", activity: "Publicación y distribución de contenido", emoji: "🚀" },
    ],
    universities: ["PUCP", "U. Lima", "UNMSM", "UPC", "USMP", "UP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Cubriendo una noticia o produciendo contenido multimedia.",
    scene: ["🎙️", "📰", "🎬", "📱", "✍️"],
    tools: ["Adobe Premiere", "Audacity", "Canva", "WordPress", "Redes sociales"],
  },
  {
    id: "comunicacion-publicidad",
    title: "Comunicación y Publicidad",
    area: "Humanidades",
    emoji: "📢",
    color: "#e11d48",
    lightBg: "#fff1f2",
    description: "Creas campañas publicitarias que conectan marcas con audiencias. Combina estrategia de comunicación, creatividad publicitaria y análisis de medios para impactar al consumidor.",
    salary: "S/. 2,500 – 9,000",
    salaryMin: 2500,
    skills: ["Creatividad", "Redacción publicitaria", "Estrategia de medios", "Análisis de audiencias", "Storytelling"],
    skillRequirements: [
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Redacción publicitaria", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Estrategia de medios", requiredLevel: "basico", category: "tecnica" },
      { name: "Análisis de audiencias", requiredLevel: "basico", category: "academica" },
      { name: "Storytelling", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Briefing creativo con el equipo de campaña", emoji: "💡" },
      { time: "10:00 am", activity: "Brainstorming de concepto publicitario", emoji: "🎨" },
      { time: "11:30 am", activity: "Revisión de piezas con director de arte", emoji: "🖌️" },
      { time: "1:00 pm", activity: "Almuerzo viendo tendencias del mercado", emoji: "🍱" },
      { time: "2:30 pm", activity: "Presentación de campaña al cliente", emoji: "🗣️" },
      { time: "4:00 pm", activity: "Coordinación con medios para pauta", emoji: "📊" },
      { time: "5:30 pm", activity: "Análisis de resultados de campaña activa", emoji: "📈" },
    ],
    universities: ["U. Lima", "PUCP", "UPC", "USIL", "UP", "UNMSM"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Creando campañas publicitarias o presentando propuestas creativas.",
    scene: ["📢", "🎨", "💡", "📊", "🎯"],
    tools: ["Meta Ads", "Google Ads", "Canva", "Photoshop", "Premiere"],
  },
  {
    id: "educacion-inicial",
    title: "Educación Inicial",
    area: "Educación",
    emoji: "🧸",
    color: "#f43f5e",
    lightBg: "#fff1f2",
    description: "Formas a niños de 0 a 6 años en sus primeros años de vida. Estimulas su desarrollo cognitivo, emocional y social. La etapa más importante de la educación.",
    salary: "S/. 1,800 – 5,000",
    salaryMin: 1800,
    skills: ["Paciencia", "Creatividad", "Psicología infantil", "Comunicación", "Didáctica lúdica"],
    skillRequirements: [
      { name: "Paciencia", requiredLevel: "intermedio", category: "blanda" },
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Psicología infantil", requiredLevel: "intermedio", category: "academica" },
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Didáctica lúdica", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Recibes a los niños con actividades de bienvenida", emoji: "👋" },
      { time: "9:00 am", activity: "Taller de arte y estimulación temprana", emoji: "🎨" },
      { time: "10:00 am", activity: "Juego libre y recreo guiado", emoji: "🧸" },
      { time: "11:00 am", activity: "Cuentacuentos y desarrollo del lenguaje", emoji: "📖" },
      { time: "12:00 pm", activity: "Almuerzo y hábitos de higiene", emoji: "🍎" },
      { time: "2:00 pm", activity: "Siesta y descanso de los pequeños", emoji: "😴" },
      { time: "3:00 pm", activity: "Reunión con padres sobre avances", emoji: "👨‍👩‍👧" },
    ],
    universities: ["PUCP", "UNMSM", "UNE La Cantuta", "U. Privada del Norte", "USIL"],
    outlook: "Estable",
    duration: "5 años",
    nowDoing: "Jugando y enseñando a niños en edad inicial o preparando materiales didácticos.",
    scene: ["🧸", "🎨", "📖", "🌈", "👶"],
    tools: ["Material didáctico", "Canciones", "Juegos pedagógicos", "Fichas de trabajo"],
  },
  {
    id: "educacion-primaria",
    title: "Educación Primaria",
    area: "Educación",
    emoji: "📚",
    color: "#eab308",
    lightBg: "#fefce8",
    description: "Enseñas a niños de 6 a 12 años las bases del conocimiento. Formas lectores, escritores y pensadores críticos en la etapa escolar más transformadora.",
    salary: "S/. 2,000 – 5,500",
    salaryMin: 2000,
    skills: ["Didáctica", "Comunicación", "Empatía", "Creatividad", "Gestión de aula"],
    skillRequirements: [
      { name: "Didáctica", requiredLevel: "intermedio", category: "academica" },
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Creatividad", requiredLevel: "intermedio", category: "blanda" },
      { name: "Gestión de aula", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "7:30 am", activity: "Preparación de aula y materiales del día", emoji: "📋" },
      { time: "8:00 am", activity: "Clase de matemáticas — operaciones básicas", emoji: "🔢" },
      { time: "9:30 am", activity: "Taller de lectura y comprensión de textos", emoji: "📖" },
      { time: "11:00 am", activity: "Recreo y juegos pedagógicos al aire libre", emoji: "⚽" },
      { time: "12:00 pm", activity: "Ciencia y ambiente — experimentos divertidos", emoji: "🔬" },
      { time: "1:00 pm", activity: "Almuerzo con los estudiantes", emoji: "🍱" },
      { time: "2:30 pm", activity: "Reunión de planificación con colegas", emoji: "🤝" },
    ],
    universities: ["UNE La Cantuta", "PUCP", "UNMSM", "U. Privada del Norte", "UCV"],
    outlook: "Estable",
    duration: "5 años",
    nowDoing: "En el aula enseñando o preparando actividades pedagógicas.",
    scene: ["📚", "✏️", "🏫", "🌟", "🔢"],
    tools: ["Pizarra digital", "Google Classroom", "Material didáctico", "Kahoot"],
  },
  {
    id: "ingenieria-biomedica",
    title: "Ingeniería Biomédica",
    area: "Ingeniería",
    emoji: "🦾",
    color: "#0ea5e9",
    lightBg: "#f0f9ff",
    description: "Combina ingeniería y medicina para crear tecnología que salva vidas. Diseñas equipos médicos, prótesis, sistemas de diagnóstico y dispositivos implantables.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Biología", "Electrónica", "Diseño de dispositivos", "Programación", "Anatomía"],
    skillRequirements: [
      { name: "Biología", requiredLevel: "intermedio", category: "academica" },
      { name: "Electrónica", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Diseño de dispositivos", requiredLevel: "basico", category: "tecnica" },
      { name: "Programación", requiredLevel: "basico", category: "tecnica" },
      { name: "Anatomía", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión de prototipo de dispositivo médico", emoji: "🔬" },
      { time: "10:30 am", activity: "Pruebas de laboratorio con equipo nuevo", emoji: "🖥️" },
      { time: "12:00 pm", activity: "Reunión con médicos para validar requerimientos", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de papers de bioingeniería", emoji: "🍱" },
      { time: "2:30 pm", activity: "Diseño de circuito o software embebido", emoji: "⚡" },
      { time: "4:00 pm", activity: "Documentación técnica para aprobación regulatoria", emoji: "📋" },
      { time: "5:30 pm", activity: "Calibración de equipos de diagnóstico", emoji: "🔧" },
    ],
    universities: ["UNI", "PUCP", "UTEC", "UPC", "UNMSM"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Diseñando dispositivos médicos o realizando pruebas de laboratorio.",
    scene: ["🦾", "🔬", "💊", "⚡", "🏥"],
    tools: ["MATLAB", "SolidWorks", "Arduino", "Impresión 3D", "Python"],
  },
  {
    id: "ingenieria-ciberseguridad",
    title: "Ingeniería de Ciberseguridad",
    area: "Tecnología",
    emoji: "🔐",
    color: "#1e293b",
    lightBg: "#f8fafc",
    description: "Proteges sistemas, redes y datos contra ataques cibernéticos. Eres el guardián digital de empresas, gobiernos y personas en un mundo cada vez más conectado.",
    salary: "S/. 5,000 – 18,000",
    salaryMin: 5000,
    skills: ["Redes", "Criptografía", "Ethical hacking", "Programación", "Análisis forense"],
    skillRequirements: [
      { name: "Redes", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Criptografía", requiredLevel: "intermedio", category: "academica" },
      { name: "Ethical hacking", requiredLevel: "basico", category: "tecnica" },
      { name: "Programación", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Análisis forense", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión de logs de seguridad y alerts SIEM", emoji: "🖥️" },
      { time: "10:30 am", activity: "Prueba de penetración en nueva aplicación", emoji: "🔍" },
      { time: "12:00 pm", activity: "Reunión de respuesta a incidentes", emoji: "🚨" },
      { time: "1:00 pm", activity: "Almuerzo y estudio de nuevas vulnerabilidades", emoji: "🍱" },
      { time: "2:30 pm", activity: "Implementación de controles de seguridad", emoji: "🛡️" },
      { time: "4:00 pm", activity: "Capacitación al equipo en phishing y buenas prácticas", emoji: "📋" },
      { time: "5:30 pm", activity: "Reporte de métricas de seguridad", emoji: "📊" },
    ],
    universities: ["UNI", "UTEC", "PUCP", "UPC", "USMP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Monitoreando la seguridad de la red o realizando pruebas de intrusión.",
    scene: ["🔐", "🛡️", "🔍", "🖥️", "🔑"],
    tools: ["Kali Linux", "Wireshark", "Firewalls", "SIEM", "Python"],
  },
  {
    id: "ingenieria-diseno-grafico",
    title: "Ingeniería de Diseño Gráfico",
    area: "Diseño",
    emoji: "🎨",
    color: "#db2777",
    lightBg: "#fdf2f8",
    description: "Comunicas visualmente ideas y conceptos mediante tipografía, ilustración, fotografía y diseño digital. Creas identidades visuales que marcan la diferencia.",
    salary: "S/. 2,500 – 9,000",
    salaryMin: 2500,
    skills: ["Creatividad visual", "Illustrator", "Photoshop", "Tipografía", "Teoría del color"],
    skillRequirements: [
      { name: "Creatividad visual", requiredLevel: "intermedio", category: "blanda" },
      { name: "Illustrator", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Photoshop", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Tipografía", requiredLevel: "basico", category: "tecnica" },
      { name: "Teoría del color", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión brief y referencias visuales", emoji: "📎" },
      { time: "10:00 am", activity: "Diseño de piezas gráficas para campaña", emoji: "🎨" },
      { time: "12:00 pm", activity: "Presentación de propuestas al cliente", emoji: "🗣️" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de tendencias de diseño", emoji: "🍱" },
      { time: "2:30 pm", activity: "Ilustración vectorial y retoque fotográfico", emoji: "🖌️" },
      { time: "4:00 pm", activity: "Diseño de branding y guía de uso", emoji: "📐" },
      { time: "5:30 pm", activity: "Preparación de archivos para imprenta", emoji: "🖨️" },
    ],
    universities: ["Toulouse Lautrec", "ISIL", "PUCP", "U. Lima", "UPC"],
    outlook: "Alta",
    duration: "4-5 años",
    nowDoing: "Diseñando piezas visuales o creando identidades de marca.",
    scene: ["🎨", "🖌️", "📐", "✨", "🖥️"],
    tools: ["Illustrator", "Photoshop", "InDesign", "Figma", "After Effects"],
  },
  {
    id: "ingenieria-sistemas-informacion",
    title: "Ingeniería de Sistemas de Información",
    area: "Tecnología",
    emoji: "🗄️",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description: "Diseñas e implementas sistemas de información que gestionan datos críticos para las organizaciones. Integras tecnología con procesos de negocio para la toma de decisiones.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Bases de datos", "Análisis de sistemas", "Programación", "Gestión de proyectos", "Seguridad informática"],
    skillRequirements: [
      { name: "Bases de datos", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Análisis de sistemas", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Programación", requiredLevel: "basico", category: "tecnica" },
      { name: "Gestión de proyectos", requiredLevel: "basico", category: "blanda" },
      { name: "Seguridad informática", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión de requerimientos con el área usuaria", emoji: "🗣️" },
      { time: "10:30 am", activity: "Diseño de arquitectura de base de datos", emoji: "🗄️" },
      { time: "12:00 pm", activity: "Implementación de módulo del sistema", emoji: "⌨️" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de nuevas tecnologías", emoji: "🍱" },
      { time: "2:30 pm", activity: "Pruebas de integración del sistema", emoji: "🖥️" },
      { time: "4:00 pm", activity: "Reunión de avance con stakeholders", emoji: "📊" },
      { time: "5:30 pm", activity: "Documentación técnica del sistema", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UPC", "USMP", "U. Lima"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Diseñando o implementando sistemas de información empresariales.",
    scene: ["🗄️", "🖥️", "📊", "🔧", "🌐"],
    tools: ["SQL", "Java", "Spring Boot", "AWS", "PowerBI"],
  },
  {
    id: "ingenieria-sistemas",
    title: "Ingeniería de Sistemas",
    area: "Tecnología",
    emoji: "⚙️",
    color: "#475569",
    lightBg: "#f8fafc",
    description: "Gestionas la infraestructura tecnológica de las organizaciones. Integras hardware, software, redes y personas para que los sistemas funcionen de manera óptima.",
    salary: "S/. 3,500 – 13,000",
    salaryMin: 3500,
    skills: ["Redes", "Administración de servidores", "Cloud computing", "Seguridad", "DevOps"],
    skillRequirements: [
      { name: "Redes", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Administración de servidores", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Cloud computing", requiredLevel: "basico", category: "tecnica" },
      { name: "Seguridad", requiredLevel: "basico", category: "tecnica" },
      { name: "DevOps", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Monitoreo de servidores y servicios cloud", emoji: "🖥️" },
      { time: "10:00 am", activity: "Resolución de tickets de infraestructura", emoji: "🔧" },
      { time: "11:30 am", activity: "Despliegue de actualizaciones de software", emoji: "🚀" },
      { time: "1:00 pm", activity: "Almuerzo y estudio de certificación técnica", emoji: "🍱" },
      { time: "2:30 pm", activity: "Optimización de rendimiento de base de datos", emoji: "📊" },
      { time: "4:00 pm", activity: "Revisión de backups y plan de contingencia", emoji: "💾" },
      { time: "5:30 pm", activity: "Documentación de procedimientos y cambios", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UPC", "USMP", "U. Lima"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Administrando servidores o gestionando infraestructura cloud.",
    scene: ["⚙️", "🖥️", "☁️", "🔧", "🌐"],
    tools: ["Linux", "AWS", "Docker", "Kubernetes", "Terraform"],
  },
  {
    id: "ingenieria-transporte",
    title: "Ingeniería de Transporte",
    area: "Ingeniería",
    emoji: "🚆",
    color: "#2563eb",
    lightBg: "#eff6ff",
    description: "Diseñas sistemas de transporte eficientes y sostenibles. Planificas redes viales, sistemas de tránsito, logística de carga y movilidad urbana.",
    salary: "S/. 4,000 – 13,000",
    salaryMin: 4000,
    skills: ["Matemáticas", "Diseño de vías", "Logística", "SIG", "Seguridad vial"],
    skillRequirements: [
      { name: "Matemáticas", requiredLevel: "intermedio", category: "academica" },
      { name: "Diseño de vías", requiredLevel: "basico", category: "tecnica" },
      { name: "Logística", requiredLevel: "intermedio", category: "tecnica" },
      { name: "SIG", requiredLevel: "basico", category: "tecnica" },
      { name: "Seguridad vial", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Análisis de flujo vehicular y datos de tránsito", emoji: "📊" },
      { time: "9:30 am", activity: "Diseño de intersección o intercambio vial", emoji: "📐" },
      { time: "11:00 am", activity: "Reunión con autoridades de transporte", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de normativa de transporte", emoji: "🍱" },
      { time: "2:30 pm", activity: "Visita a campo para estudio de tráfico", emoji: "🏗️" },
      { time: "4:00 pm", activity: "Modelamiento de redes de transporte", emoji: "🖥️" },
      { time: "5:30 pm", activity: "Informe técnico de propuesta de mejora", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UNMSM", "UPC", "U. Piura"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Analizando datos de tránsito o diseñando soluciones de movilidad.",
    scene: ["🚆", "🚌", "🏗️", "📐", "🗺️"],
    tools: ["AutoCAD", "Vissim", "ArcGIS", "SIG", "Excel avanzado"],
  },
  {
    id: "ingenieria-economica-negocios",
    title: "Ingeniería Económica y de Negocios",
    area: "Negocios",
    emoji: "📈",
    color: "#16a34a",
    lightBg: "#f0fdf4",
    description: "Aplicas principios de ingeniería a la toma de decisiones económicas y financieras. Evalúas proyectos de inversión, gestionas riesgos y optimizas recursos empresariales.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Análisis financiero", "Estadística", "Evaluación de proyectos", "Modelamiento", "Pensamiento estratégico"],
    skillRequirements: [
      { name: "Análisis financiero", requiredLevel: "intermedio", category: "academica" },
      { name: "Estadística", requiredLevel: "intermedio", category: "academica" },
      { name: "Evaluación de proyectos", requiredLevel: "basico", category: "tecnica" },
      { name: "Modelamiento", requiredLevel: "basico", category: "tecnica" },
      { name: "Pensamiento estratégico", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión de indicadores financieros del negocio", emoji: "📈" },
      { time: "10:30 am", activity: "Evaluación de proyecto de inversión", emoji: "📊" },
      { time: "12:00 pm", activity: "Reunión con gerencia de finanzas", emoji: "🤝" },
      { time: "1:00 pm", activity: "Almuerzo y análisis de mercado", emoji: "🍱" },
      { time: "2:30 pm", activity: "Modelamiento financiero en Excel", emoji: "💹" },
      { time: "4:00 pm", activity: "Presentación de resultados económicos", emoji: "📑" },
      { time: "5:30 pm", activity: "Análisis de riesgos y escenarios", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "U. Lima", "UPC", "ESAN", "UP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Evaluando proyectos de inversión o modelando escenarios financieros.",
    scene: ["📈", "💹", "📊", "💰", "🏦"],
    tools: ["Excel", "SAP", "PowerBI", "Python", "Stata"],
  },
  {
    id: "ingenieria-electronica",
    title: "Ingeniería Electrónica",
    area: "Ingeniería",
    emoji: "⚡",
    color: "#d97706",
    lightBg: "#fffbeb",
    description: "Diseñas circuitos, sistemas de control y dispositivos electrónicos. Desde microcontroladores hasta sistemas de automatización industrial, tu trabajo está en todas partes.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Circuitos eléctricos", "Programación embebida", "Diseño de PCB", "Control y automatización", "Matemáticas"],
    skillRequirements: [
      { name: "Circuitos eléctricos", requiredLevel: "intermedio", category: "academica" },
      { name: "Programación embebida", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Diseño de PCB", requiredLevel: "basico", category: "tecnica" },
      { name: "Control y automatización", requiredLevel: "basico", category: "tecnica" },
      { name: "Matemáticas", requiredLevel: "intermedio", category: "academica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Simulación de circuito en software especializado", emoji: "🖥️" },
      { time: "10:30 am", activity: "Diseño de placa PCB en Altium", emoji: "⚡" },
      { time: "12:00 pm", activity: "Pruebas de prototipo en laboratorio", emoji: "🔬" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de componentes", emoji: "🍱" },
      { time: "2:30 pm", activity: "Programación de microcontrolador", emoji: "⌨️" },
      { time: "4:00 pm", activity: "Reunión técnica con equipo de desarrollo", emoji: "🤝" },
      { time: "5:30 pm", activity: "Documentación de diseño e informes de prueba", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UTEC", "UPC", "UNMSM"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Diseñando circuitos o programando sistemas embebidos.",
    scene: ["⚡", "🔬", "🖥️", "⚙️", "🔧"],
    tools: ["Altium Designer", "MATLAB", "Arduino", "FPGA", "Python"],
  },
  {
    id: "ingenieria-empresarial",
    title: "Ingeniería Empresarial",
    area: "Negocios",
    emoji: "🏢",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description: "Optimizas procesos empresariales usando principios de ingeniería. Mejoras la productividad, gestionas proyectos y lideras la transformación digital de las organizaciones.",
    salary: "S/. 3,500 – 12,000",
    salaryMin: 3500,
    skills: ["Gestión de procesos", "Análisis de datos", "Liderazgo", "Gestión de proyectos", "Innovación"],
    skillRequirements: [
      { name: "Gestión de procesos", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Análisis de datos", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Liderazgo", requiredLevel: "intermedio", category: "blanda" },
      { name: "Gestión de proyectos", requiredLevel: "basico", category: "blanda" },
      { name: "Innovación", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión de KPIs y dashboard empresarial", emoji: "📊" },
      { time: "10:00 am", activity: "Reunión de mejora continua con equipos", emoji: "🗣️" },
      { time: "11:30 am", activity: "Análisis de procesos y propuesta de optimización", emoji: "🔍" },
      { time: "1:00 pm", activity: "Almuerzo con colegas de otros departamentos", emoji: "🍱" },
      { time: "2:30 pm", activity: "Implementación de proyecto de innovación", emoji: "💡" },
      { time: "4:00 pm", activity: "Capacitación al equipo en nuevas herramientas", emoji: "📋" },
      { time: "5:30 pm", activity: "Reporte de avance a la gerencia", emoji: "📈" },
    ],
    universities: ["UNI", "PUCP", "U. Lima", "UPC", "ESAN", "UP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Analizando procesos empresariales o liderando proyectos de mejora.",
    scene: ["🏢", "📊", "💡", "🤝", "📈"],
    tools: ["Excel", "SAP", "PowerBI", "Visio", "Jira"],
  },
  {
    id: "ingenieria-maritima",
    title: "Ingeniería Marítima",
    area: "Ingeniería",
    emoji: "🚢",
    color: "#0d9488",
    lightBg: "#f0fdfa",
    description: "Diseñas, construyes y mantienes embarcaciones, puertos e infraestructura marítima. Gestionas operaciones portuarias y sistemas de navegación en el mar peruano.",
    salary: "S/. 4,500 – 15,000",
    salaryMin: 4500,
    skills: ["Arquitectura naval", "Mecánica", "Hidráulica", "Gestión portuaria", "Soldadura"],
    skillRequirements: [
      { name: "Arquitectura naval", requiredLevel: "basico", category: "tecnica" },
      { name: "Mecánica", requiredLevel: "intermedio", category: "academica" },
      { name: "Hidráulica", requiredLevel: "intermedio", category: "academica" },
      { name: "Gestión portuaria", requiredLevel: "basico", category: "tecnica" },
      { name: "Soldadura", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Inspección de embarcaciones en astillero", emoji: "🚢" },
      { time: "9:30 am", activity: "Revisión de planos de construcción naval", emoji: "📐" },
      { time: "11:00 am", activity: "Coordinación de operaciones portuarias", emoji: "🗣️" },
      { time: "1:00 pm", activity: "Almuerzo en puerto o astillero", emoji: "🍱" },
      { time: "2:30 pm", activity: "Diseño de sistemas de propulsión", emoji: "⚙️" },
      { time: "4:00 pm", activity: "Supervisión de mantenimiento de flota", emoji: "🔧" },
      { time: "5:30 pm", activity: "Reporte de operaciones marítimas", emoji: "📋" },
    ],
    universities: ["UNI", "U. Nacional del Callao", "PUCP", "USMP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Supervisando construcción naval o gestionando operaciones portuarias.",
    scene: ["🚢", "⚓", "🌊", "📐", "🔧"],
    tools: ["AutoCAD", "SolidWorks", "SAP", "Sistemas de navegación"],
  },
  {
    id: "ingenieria-mecanica",
    title: "Ingeniería Mecánica",
    area: "Ingeniería",
    emoji: "🔧",
    color: "#64748b",
    lightBg: "#f8fafc",
    description: "Diseñas y mantienes maquinaria, sistemas térmicos y equipos mecánicos. Desde motores hasta plantas industriales, tu trabajo mueve la industria.",
    salary: "S/. 4,000 – 14,000",
    salaryMin: 4000,
    skills: ["Física", "Diseño mecánico", "Termodinámica", "CAD", "Materiales"],
    skillRequirements: [
      { name: "Física", requiredLevel: "intermedio", category: "academica" },
      { name: "Diseño mecánico", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Termodinámica", requiredLevel: "intermedio", category: "academica" },
      { name: "CAD", requiredLevel: "basico", category: "tecnica" },
      { name: "Materiales", requiredLevel: "intermedio", category: "academica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisión de planos y especificaciones técnicas", emoji: "📐" },
      { time: "9:30 am", activity: "Diseño de pieza mecánica en SolidWorks", emoji: "🖥️" },
      { time: "11:00 am", activity: "Supervisión de taller de mantenimiento", emoji: "🔧" },
      { time: "1:00 pm", activity: "Almuerzo con equipo de ingeniería", emoji: "🍱" },
      { time: "2:30 pm", activity: "Análisis de falla de equipo industrial", emoji: "🔍" },
      { time: "4:00 pm", activity: "Selección de materiales y componentes", emoji: "⚙️" },
      { time: "5:30 pm", activity: "Informe técnico de mantenimiento preventivo", emoji: "📋" },
    ],
    universities: ["UNI", "PUCP", "UPC", "UNMSM", "U. Piura"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Diseñando componentes mecánicos o supervisando mantenimiento industrial.",
    scene: ["🔧", "⚙️", "🖥️", "📐", "🏭"],
    tools: ["SolidWorks", "AutoCAD", "MATLAB", "ANSYS", "Inventor"],
  },
  {
    id: "ingenieria-mecatronica",
    title: "Ingeniería Mecatrónica",
    area: "Ingeniería",
    emoji: "🤖",
    color: "#0ea5e9",
    lightBg: "#f0f9ff",
    description: "Integras mecánica, electrónica y programación para crear sistemas inteligentes. Robots, vehículos autónomos, fábricas automatizadas — el futuro es mecatrónico.",
    salary: "S/. 4,500 – 15,000",
    salaryMin: 4500,
    skills: ["Robótica", "Programación", "Electrónica", "Mecánica", "Control automático"],
    skillRequirements: [
      { name: "Robótica", requiredLevel: "basico", category: "tecnica" },
      { name: "Programación", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Electrónica", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Mecánica", requiredLevel: "intermedio", category: "academica" },
      { name: "Control automático", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Programación de robot industrial para nueva tarea", emoji: "🤖" },
      { time: "10:30 am", activity: "Prueba de sensores y actuadores", emoji: "⚡" },
      { time: "12:00 pm", activity: "Reunión de diseño de nuevo sistema automatizado", emoji: "🗣️" },
      { time: "1:00 pm", activity: "Almuerzo viendo tecnología de automatización", emoji: "🍱" },
      { time: "2:30 pm", activity: "Diseño de sistema embebido en PCB", emoji: "🖥️" },
      { time: "4:00 pm", activity: "Calibración de sistema de visión artificial", emoji: "📷" },
      { time: "5:30 pm", activity: "Documentación técnica del sistema integrado", emoji: "📋" },
    ],
    universities: ["UNI", "UTEC", "PUCP", "UPC", "U. Lima"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Programando robots o integrando sistemas mecatrónicos.",
    scene: ["🤖", "⚡", "⚙️", "🖥️", "🔧"],
    tools: ["ROS", "Arduino", "Python", "SolidWorks", "MATLAB"],
  },
  {
    id: "ingenieria-naval",
    title: "Ingeniería Naval",
    area: "Ingeniería",
    emoji: "⚓",
    color: "#1d4ed8",
    lightBg: "#eff6ff",
    description: "Diseñas y construyes buques, submarinos y estructuras oceánicas. Eres responsable de la arquitectura naval, estabilidad de embarcaciones y sistemas de navegación.",
    salary: "S/. 5,000 – 16,000",
    salaryMin: 5000,
    skills: ["Hidrodinámica", "Arquitectura naval", "Estructuras marinas", "Diseño asistido", "Materiales marinos"],
    skillRequirements: [
      { name: "Hidrodinámica", requiredLevel: "intermedio", category: "academica" },
      { name: "Arquitectura naval", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Estructuras marinas", requiredLevel: "basico", category: "academica" },
      { name: "Diseño asistido", requiredLevel: "basico", category: "tecnica" },
      { name: "Materiales marinos", requiredLevel: "basico", category: "academica" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Revisión de cálculos de estabilidad de buque", emoji: "📐" },
      { time: "9:30 am", activity: "Diseño de sección estructural del casco", emoji: "🖥️" },
      { time: "11:00 am", activity: "Supervisión de construcción en astillero", emoji: "🚢" },
      { time: "1:00 pm", activity: "Almuerzo con supervisores de obra naval", emoji: "🍱" },
      { time: "2:30 pm", activity: "Simulación hidrodinámica de embarcación", emoji: "💻" },
      { time: "4:00 pm", activity: "Revisión de normativa de seguridad marítima", emoji: "📋" },
      { time: "5:30 pm", activity: "Informe de avance de construcción", emoji: "📊" },
    ],
    universities: ["UNI", "U. Nacional del Callao", "PUCP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Diseñando embarcaciones o supervisando construcción en astillero.",
    scene: ["⚓", "🚢", "🌊", "📐", "🔧"],
    tools: ["AutoCAD", "Maxsurf", "SolidWorks", "SAP2000", "Ansys"],
  },
  {
    id: "obstetricia",
    title: "Obstetricia",
    area: "Salud",
    emoji: "🤰",
    color: "#e11d48",
    lightBg: "#fff1f2",
    description: "Acompañas a la mujer durante el embarazo, parto y postparto. Promueves la salud materno-infantil y realizas atención integral en todas las etapas reproductivas.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Empatía", "Precisión clínica", "Anatomía", "Comunicación", "Trabajo bajo presión"],
    skillRequirements: [
      { name: "Empatía", requiredLevel: "intermedio", category: "blanda" },
      { name: "Precisión clínica", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Anatomía", requiredLevel: "intermedio", category: "academica" },
      { name: "Comunicación", requiredLevel: "intermedio", category: "blanda" },
      { name: "Trabajo bajo presión", requiredLevel: "intermedio", category: "blanda" },
    ],
    dayInLife: [
      { time: "7:00 am", activity: "Visita a pacientes hospitalizadas en ginecología", emoji: "🏥" },
      { time: "9:00 am", activity: "Atención de consultas prenatales", emoji: "🤰" },
      { time: "11:00 am", activity: "Ecografías obstétricas y monitoreo fetal", emoji: "📊" },
      { time: "1:00 pm", activity: "Almuerzo entre guardias", emoji: "🍱" },
      { time: "2:00 pm", activity: "Atención de parto o procedimiento obstétrico", emoji: "👶" },
      { time: "4:00 pm", activity: "Consejería en planificación familiar", emoji: "🗣️" },
      { time: "5:30 pm", activity: "Registro de historias clínicas", emoji: "📝" },
    ],
    universities: ["UNMSM", "UPCH", "USMP", "URP", "U. Nacional del Callao"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Atendiendo consultas prenatales o acompañando un parto.",
    scene: ["🤰", "👶", "🏥", "💗", "📊"],
    tools: ["Ecógrafo", "Monitor fetal", "Historias clínicas", "Equipos de parto"],
  },
  {
    id: "psicologia-consumidor",
    title: "Psicología del Consumidor",
    area: "Negocios",
    emoji: "🛍️",
    color: "#f43f5e",
    lightBg: "#fff1f2",
    description: "Investigas el comportamiento de compra y toma de decisiones de los consumidores. Aplicas principios psicológicos al marketing, publicidad y estrategia comercial.",
    salary: "S/. 3,000 – 10,000",
    salaryMin: 3000,
    skills: ["Análisis de comportamiento", "Investigación de mercados", "Estadística", "Psicología social", "Storytelling"],
    skillRequirements: [
      { name: "Análisis de comportamiento", requiredLevel: "intermedio", category: "academica" },
      { name: "Investigación de mercados", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Estadística", requiredLevel: "basico", category: "academica" },
      { name: "Psicología social", requiredLevel: "intermedio", category: "academica" },
      { name: "Storytelling", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Análisis de datos de comportamiento de usuarios", emoji: "📊" },
      { time: "10:30 am", activity: "Diseño de estudio de focus group", emoji: "📋" },
      { time: "12:00 pm", activity: "Moderación de sesión con consumidores", emoji: "🎙️" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de tendencias de consumo", emoji: "🍱" },
      { time: "2:30 pm", activity: "Segmentación psicográfica de audiencias", emoji: "🎯" },
      { time: "4:00 pm", activity: "Presentación de insights al equipo de marketing", emoji: "📈" },
      { time: "5:30 pm", activity: "Recomendaciones de estrategia basadas en data", emoji: "✍️" },
    ],
    universities: ["PUCP", "U. Lima", "UPC", "USIL", "UP"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Analizando comportamiento del consumidor o realizando estudios de mercado.",
    scene: ["🛍️", "📊", "🎯", "💡", "📋"],
    tools: ["SPSS", "Google Analytics", "Qualtrics", "NVivo", "Excel"],
  },
  {
    id: "redes-telecomunicaciones",
    title: "Redes y Telecomunicaciones",
    area: "Tecnología",
    emoji: "📡",
    color: "#0891b2",
    lightBg: "#ecfeff",
    description: "Diseñas, implementas y gestionas redes de comunicación. Desde fibra óptica hasta 5G, conectas personas y dispositivos a escala nacional y global.",
    salary: "S/. 3,500 – 13,000",
    salaryMin: 3500,
    skills: ["Redes IP", "Fibra óptica", "Comunicaciones inalámbricas", "Seguridad de redes", "Administración de equipos"],
    skillRequirements: [
      { name: "Redes IP", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Fibra óptica", requiredLevel: "basico", category: "tecnica" },
      { name: "Comunicaciones inalámbricas", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Seguridad de redes", requiredLevel: "basico", category: "tecnica" },
      { name: "Administración de equipos", requiredLevel: "basico", category: "tecnica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Monitoreo de red y análisis de tráfico", emoji: "🖥️" },
      { time: "10:00 am", activity: "Configuración de routers y switches", emoji: "🔧" },
      { time: "11:30 am", activity: "Diagnóstico de incidencia de conectividad", emoji: "🔍" },
      { time: "1:00 pm", activity: "Almuerzo y estudio de nuevas tecnologías", emoji: "🍱" },
      { time: "2:30 pm", activity: "Optimización de red inalámbrica", emoji: "📡" },
      { time: "4:00 pm", activity: "Reunión con proveedor de servicios", emoji: "🤝" },
      { time: "5:30 pm", activity: "Reporte de disponibilidad y rendimiento", emoji: "📊" },
    ],
    universities: ["UNI", "PUCP", "UPC", "USMP", "UTEC"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Gestionando redes de comunicación o configurando equipos de telecomunicaciones.",
    scene: ["📡", "🖥️", "🔧", "🌐", "📊"],
    tools: ["Cisco IOS", "Wireshark", "Fibra óptica", "Redes 5G", "SNMP"],
  },
  {
    id: "tecnologia-medica",
    title: "Tecnología Médica",
    area: "Salud",
    emoji: "🔬",
    color: "#0ea5e9",
    lightBg: "#f0f9ff",
    description: "Operas y gestionas equipos de diagnóstico y tratamiento médico. Rayos X, tomógrafos, resonadores — eres el experto que hace funcionar la tecnología que salva vidas.",
    salary: "S/. 2,500 – 8,000",
    salaryMin: 2500,
    skills: ["Anatomía", "Física médica", "Operación de equipos", "Protección radiológica", "Atención al paciente"],
    skillRequirements: [
      { name: "Anatomía", requiredLevel: "intermedio", category: "academica" },
      { name: "Física médica", requiredLevel: "intermedio", category: "academica" },
      { name: "Operación de equipos", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Protección radiológica", requiredLevel: "basico", category: "tecnica" },
      { name: "Atención al paciente", requiredLevel: "basico", category: "blanda" },
    ],
    dayInLife: [
      { time: "8:00 am", activity: "Calibración de equipos de diagnóstico", emoji: "🖥️" },
      { time: "9:00 am", activity: "Toma de radiografías o tomografías", emoji: "💀" },
      { time: "11:00 am", activity: "Procesamiento de imágenes médicas", emoji: "🔬" },
      { time: "1:00 pm", activity: "Almuerzo y revisión de protocolos", emoji: "🍱" },
      { time: "2:00 pm", activity: "Atención de pacientes para ecografías", emoji: "📊" },
      { time: "4:00 pm", activity: "Mantenimiento preventivo de equipos", emoji: "🔧" },
      { time: "5:30 pm", activity: "Registro de procedimientos realizados", emoji: "📝" },
    ],
    universities: ["UNMSM", "UPCH", "URP", "USMP", "U. Nacional del Callao"],
    outlook: "Alta",
    duration: "5 años",
    nowDoing: "Operando equipos de diagnóstico o procesando imágenes médicas.",
    scene: ["🔬", "💀", "🏥", "📊", "🩻"],
    tools: ["Tomógrafo", "Resonador", "Ecógrafo", "Rayos X", "RIS/PACS"],
  },
  {
    id: "traduccion-interpretacion",
    title: "Traducción e Interpretación",
    area: "Humanidades",
    emoji: "🌐",
    color: "#7c3aed",
    lightBg: "#f5f3ff",
    description: "Traduces documentos y/o interpretas en tiempo real entre idiomas. Eres el puente lingüístico en negociaciones internacionales, conferencias, tribunales y medios.",
    salary: "S/. 2,500 – 9,000",
    salaryMin: 2500,
    skills: ["Dominio de idiomas (mínimo 3)", "Traducción escrita", "Interpretación simultánea", "Investigación terminológica", "Conocimiento cultural"],
    skillRequirements: [
      { name: "Dominio de idiomas (mínimo 3)", requiredLevel: "avanzado", category: "academica" },
      { name: "Traducción escrita", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Interpretación simultánea", requiredLevel: "basico", category: "tecnica" },
      { name: "Investigación terminológica", requiredLevel: "intermedio", category: "tecnica" },
      { name: "Conocimiento cultural", requiredLevel: "intermedio", category: "academica" },
    ],
    dayInLife: [
      { time: "9:00 am", activity: "Revisión de documentos para traducción especializada", emoji: "📄" },
      { time: "10:00 am", activity: "Traducción de contrato legal inglés-español", emoji: "✍️" },
      { time: "12:00 pm", activity: "Preparación de glosario de términos técnicos", emoji: "📚" },
      { time: "1:00 pm", activity: "Almuerzo y práctica de interpretación", emoji: "🍱" },
      { time: "2:30 pm", activity: "Interpretación simultánea en reunión ejecutiva", emoji: "🎧" },
      { time: "4:00 pm", activity: "Corrección de estilo y revisión de traducciones", emoji: "🔍" },
      { time: "5:30 pm", activity: "Entrega de traducción urgente al cliente", emoji: "📨" },
    ],
    universities: ["PUCP", "U. Lima", "UNMSM", "UPC", "USMP"],
    outlook: "Media",
    duration: "5 años",
    nowDoing: "Traduciendo documentos especializados o interpretando en una reunión internacional.",
    scene: ["🌐", "📄", "🎧", "✍️", "🌍"],
    tools: ["Trados", "MemoQ", "DeepL", "CAI tools", "Grabadoras digitales"],
  },
];
